# api/scanner/stock_universe.py

"""
Comprehensive US Stock Universe for Market Scanning

Total: ~3,500+ stocks covering:
- S&P 500 (Large Cap)
- S&P 400 (Mid Cap)  
- S&P 600 (Small Cap)
- Russell 2000 components
- Popular micro caps & growth stocks
- Major ETFs

Last Updated: January 2026
"""

# ═══════════════════════════════════════════════════════════════════════════════
# S&P 500 - LARGE CAP (~500 stocks)
# ═══════════════════════════════════════════════════════════════════════════════

SP500 = [
    "A", "AAL", "AAPL", "ABBV", "ABNB", "ABT", "ACGL", "ACN", "ADBE", "ADI",
    "ADM", "ADP", "ADSK", "AEE", "AEP", "AES", "AFL", "AIG", "AIZ", "AJG",
    "AKAM", "ALB", "ALGN", "ALL", "ALLE", "AMAT", "AMCR", "AMD", "AME", "AMGN",
    "AMP", "AMT", "AMZN", "ANET", "ANSS", "AON", "AOS", "APA", "APD", "APH",
    "APTV", "ARE", "ATO", "AVB", "AVGO", "AVY", "AWK", "AXON", "AXP", "AZO",
    "BA", "BAC", "BALL", "BAX", "BBWI", "BBY", "BDX", "BEN", "BF-B", "BG",
    "BIIB", "BIO", "BK", "BKNG", "BKR", "BLDR", "BLK", "BMY", "BR", "BRK-B",
    "BRO", "BSX", "BWA", "BX", "BXP", "C", "CAG", "CAH", "CARR", "CAT",
    "CB", "CBOE", "CBRE", "CCI", "CCL", "CDNS", "CDW", "CE", "CEG", "CF",
    "CFG", "CHD", "CHRW", "CHTR", "CI", "CINF", "CL", "CLX", "CMA", "CMCSA",
    "CME", "CMG", "CMI", "CMS", "CNC", "CNP", "COF", "COO", "COP", "COR",
    "COST", "CPAY", "CPB", "CPRT", "CPT", "CRL", "CRM", "CSCO", "CSGP", "CSX",
    "CTAS", "CTLT", "CTRA", "CTSH", "CTVA", "CVS", "CVX", "CZR", "D", "DAL",
    "DD", "DE", "DECK", "DFS", "DG", "DGX", "DHI", "DHR", "DIS", "DLR",
    "DLTR", "DOC", "DOV", "DOW", "DPZ", "DRI", "DTE", "DUK", "DVA", "DVN",
    "DXCM", "EA", "EBAY", "ECL", "ED", "EFX", "EG", "EIX", "EL", "ELV",
    "EMN", "EMR", "ENPH", "EOG", "EPAM", "EQIX", "EQR", "EQT", "ES", "ESS",
    "ETN", "ETR", "EVRG", "EW", "EXC", "EXPD", "EXPE", "EXR", "F", "FANG",
    "FAST", "FCX", "FDS", "FDX", "FE", "FFIV", "FI", "FICO", "FIS", "FITB",
    "FLT", "FMC", "FOX", "FOXA", "FRT", "FSLR", "FTNT", "FTV", "GD", "GDDY",
    "GE", "GEHC", "GEN", "GEV", "GILD", "GIS", "GL", "GLW", "GM", "GNRC",
    "GOOG", "GOOGL", "GPC", "GPN", "GRMN", "GS", "GWW", "HAL", "HAS", "HBAN",
    "HCA", "HD", "HES", "HIG", "HII", "HLT", "HOLX", "HON", "HPE", "HPQ",
    "HRL", "HSIC", "HST", "HSY", "HUBB", "HUM", "HWM", "IBM", "ICE", "IDXX",
    "IEX", "IFF", "ILMN", "INCY", "INTC", "INTU", "INVH", "IP", "IPG", "IQV",
    "IR", "IRM", "ISRG", "IT", "ITW", "IVZ", "J", "JBHT", "JBL", "JCI",
    "JKHY", "JNJ", "JNPR", "JPM", "K", "KDP", "KEY", "KEYS", "KHC", "KIM",
    "KLAC", "KMB", "KMI", "KMX", "KO", "KR", "KVUE", "L", "LDOS", "LEN",
    "LH", "LHX", "LIN", "LKQ", "LLY", "LMT", "LNT", "LOW", "LRCX", "LULU",
    "LUV", "LVS", "LW", "LYB", "LYV", "MA", "MAA", "MAR", "MAS", "MCD",
    "MCHP", "MCK", "MCO", "MDLZ", "MDT", "MET", "META", "MGM", "MHK", "MKC",
    "MKTX", "MLM", "MMC", "MMM", "MNST", "MO", "MOH", "MOS", "MPC", "MPWR",
    "MRK", "MRNA", "MRO", "MS", "MSCI", "MSFT", "MSI", "MTB", "MTCH", "MTD",
    "MU", "NCLH", "NDAQ", "NDSN", "NEE", "NEM", "NFLX", "NI", "NKE", "NOC",
    "NOW", "NRG", "NSC", "NTAP", "NTRS", "NUE", "NVDA", "NVR", "NWS", "NWSA",
    "NXPI", "O", "ODFL", "OKE", "OMC", "ON", "ORCL", "ORLY", "OTIS", "OXY",
    "PANW", "PARA", "PAYC", "PAYX", "PCAR", "PCG", "PEG", "PEP", "PFE", "PFG",
    "PG", "PGR", "PH", "PHM", "PKG", "PLD", "PM", "PNC", "PNR", "PNW",
    "PODD", "POOL", "PPG", "PPL", "PRU", "PSA", "PSX", "PTC", "PWR", "PXD",
    "PYPL", "QCOM", "QRVO", "RCL", "REG", "REGN", "RF", "RJF", "RL", "RMD",
    "ROK", "ROL", "ROP", "ROST", "RSG", "RTX", "RVTY", "SBAC", "SBUX", "SCHW",
    "SHW", "SJM", "SLB", "SMCI", "SNA", "SNPS", "SO", "SOLV", "SPG", "SPGI",
    "SRE", "STE", "STLD", "STT", "STX", "STZ", "SWK", "SWKS", "SYF", "SYK",
    "SYY", "T", "TAP", "TDG", "TDY", "TECH", "TEL", "TER", "TFC", "TFX",
    "TGT", "TJX", "TMO", "TMUS", "TPR", "TRGP", "TRMB", "TROW", "TRV", "TSCO",
    "TSLA", "TSN", "TT", "TTWO", "TXN", "TXT", "TYL", "UAL", "UBER", "UDR",
    "UHS", "ULTA", "UNH", "UNP", "UPS", "URI", "USB", "V", "VFC", "VICI",
    "VLO", "VLTO", "VMC", "VRSK", "VRSN", "VRTX", "VST", "VTR", "VTRS", "VZ",
    "WAB", "WAT", "WBA", "WBD", "WDC", "WEC", "WELL", "WFC", "WM", "WMB",
    "WMT", "WRB", "WRK", "WST", "WTW", "WY", "WYNN", "XEL", "XOM", "XYL",
    "YUM", "ZBH", "ZBRA", "ZTS",
]

# ═══════════════════════════════════════════════════════════════════════════════
# S&P 400 - MID CAP (~400 stocks)
# ═══════════════════════════════════════════════════════════════════════════════

SP400_MIDCAP = [
    "AAON", "AAP", "ACIW", "ACM", "ADTN", "AEO", "AFG", "AGCO", "AIT", "ALE",
    "ALKS", "ALLY", "ALSN", "AM", "AMED", "AMG", "AMKR", "AMP", "AN", "ARMK",
    "AROC", "ARW", "ASB", "ASH", "ASGN", "ATI", "ATMU", "ATR", "AUB", "AVT",
    "AXNX", "AXTA", "AYI", "AZZ", "B", "BBIO", "BC", "BCO", "BECN", "BERY",
    "BHF", "BIO-B", "BJ", "BKH", "BL", "BLD", "BLKB", "BMI", "BOH", "BOKF",
    "BOOT", "BPMC", "BPOP", "BRBR", "BRC", "BRKR", "BWXT", "BYD", "CALM", "CAR",
    "CARG", "CASY", "CATY", "CBT", "CBU", "CC", "CCOI", "CDP", "CDR", "CEIX",
    "CFR", "CG", "CGNX", "CHE", "CHDN", "CHH", "CHRD", "CHX", "CIEN", "CIXX",
    "CKH", "CLB", "CLF", "CLH", "CMC", "CMD", "CMP", "CNK", "CNM", "CNO",
    "CNS", "CNX", "COKE", "COLB", "COLM", "COMM", "COOP", "CPE", "CPK", "CR",
    "CRAI", "CRC", "CRGY", "CRI", "CRS", "CRVL", "CSL", "CSWI", "CUBI", "CUZ",
    "CVCO", "CVLT", "CW", "CWH", "CWST", "CXW", "DAN", "DAR", "DCI", "DINO",
    "DKS", "DLB", "DNOW", "DOCN", "DOX", "DXC", "DY", "EAT", "EEFT", "EGP",
    "EHC", "ELF", "ELS", "EME", "ENSG", "ENS", "ENVX", "EPRT", "EQBK", "ESGR",
    "ESNT", "ETSY", "EVR", "EVTC", "EXEL", "EXLS", "EXP", "EXPO", "EXTR", "FAF",
    "FBIN", "FCFS", "FCNCA", "FCPT", "FHB", "FHI", "FIBK", "FIX", "FLO", "FLS",
    "FLT", "FN", "FNB", "FND", "FOCS", "FOUR", "FROG", "FRPT", "FSS", "FSTR",
    "FTDR", "FUL", "G", "GAP", "GATX", "GBX", "GEF", "GEO", "GFF", "GGG",
    "GH", "GHC", "GKOS", "GMS", "GNW", "GOLF", "GTES", "GTLS", "GVA", "GXO",
    "H", "HAE", "HAIN", "HAL", "HBI", "HGV", "HI", "HLNE", "HLX", "HNI",
    "HP", "HQY", "HR", "HRB", "HRI", "HSII", "HTGC", "HTH", "HUBG", "HUN",
    "HWC", "HXL", "IAC", "IART", "IBKR", "IBOC", "IBP", "ICFI", "ICUI", "IDCC",
    "IDA", "IEX", "IIVI", "ILPT", "INDB", "INGR", "INST", "INVA", "IONS", "IOSP",
    "IPAR", "IPGP", "IRT", "ITCI", "ITT", "JBGS", "JBT", "JEF", "JJSF", "JLL",
    "JNPR", "JOBY", "JWN", "KAI", "KBH", "KBR", "KEX", "KFY", "KGS", "KMT",
    "KNF", "KNX", "KOD", "KREF", "KRC", "KRG", "KSS", "KTB", "KW", "LAMR",
    "LANC", "LAUR", "LCM", "LEA", "LFUS", "LGIH", "LH", "LII", "LITE", "LIVN",
    "LNC", "LNTH", "LOPE", "LPLA", "LPX", "LSCC", "LSI", "LTC", "LUMN", "LW",
    "LXP", "M", "MAC", "MAN", "MANH", "MAT", "MATX", "MC", "MCY", "MDB",
    "MDGL", "MDU", "MEDP", "MHO", "MIR", "MKSI", "MLKN", "MLR", "MMSI", "MMS",
    "MNRO", "MOD", "MOG-A", "MPW", "MRC", "MRCY", "MRTN", "MSA", "MSG", "MSM",
    "MSTR", "MTDR", "MTG", "MTH", "MTN", "MTX", "MTZ", "MUR", "MUSA", "MWA",
    "MXL", "NARI", "NATL", "NBHC", "NBIX", "NBR", "NCI", "NEOG", "NEU", "NFG",
    "NGS", "NHC", "NJR", "NNN", "NOG", "NOVT", "NR", "NSA", "NSP", "NTCT",
    "NUS", "NVT", "NXRT", "NXST", "NYCB", "NYT", "OC", "ODC", "ODP", "OFC",
    "OFG", "OGE", "OGN", "OGS", "OHI", "OI", "OII", "OIS", "OLN", "OMI",
    "ONB", "ONTO", "ORA", "ORI", "OSK", "OTTR", "OUT", "OVV", "OXM", "PACW",
    "PAG", "PATK", "PAYO", "PB", "PBF", "PCRX", "PDCE", "PDM", "PECO", "PEN",
    "PENG", "PFBC", "PGC", "PII", "PINC", "PIPR", "PKE", "PLMR", "PLNT", "PLUS",
    "PLXS", "PNM", "PNFP", "PNR", "POOL", "POST", "POWI", "PPC", "PRAA", "PRFT",
    "PRGS", "PRI", "PRK", "PRLB", "PRM", "PRSP", "PRVA", "PSB", "PSN", "PSTG",
    "PVH", "PWSC", "PZZA", "QTWO", "R", "RBA", "RBC", "RDFN", "RDN", "REV",
    "REVG", "RGA", "RGEN", "RGS", "RH", "RHI", "RHP", "RIG", "RMBS", "RNR",
    "ROCK", "ROG", "RPM", "RRBI", "RRC", "RRR", "RS", "RUN", "RVI", "RVNC",
    "RXO", "SAH", "SAIA", "SANM", "SATS", "SBCF", "SBGI", "SCI", "SCL", "SCSC",
    "SEDG", "SEE", "SEIC", "SF", "SFBS", "SFNC", "SFT", "SGHC", "SIGI", "SIG",
    "SITE", "SITM", "SJW", "SKT", "SKX", "SLAB", "SLG", "SM", "SMAR", "SMCI",
    "SMG", "SMPL", "SN", "SNDR", "SNV", "SNX", "SO", "SON", "SPA", "SPNT",
    "SPSC", "SPT", "SPXC", "SR", "SRC", "SRL", "SSD", "ST", "STAG", "STC",
    "STEP", "STNG", "STR", "SUM", "SUN", "SUPN", "SWCH", "SWI", "SWN", "SWX",
    "SXT", "SXI", "SYBT", "SYF", "TALO", "TCBI", "TCO", "TDC", "TDS", "TFIN",
    "TGNA", "THC", "THG", "THO", "THS", "TKR", "TNC", "TNL", "TOL", "TPH",
    "TPX", "TREX", "TRMK", "TRN", "TRNO", "TRS", "TTEK", "TTC", "TTEC", "TTGT",
    "TTMI", "TVTX", "TXRH", "UE", "UFI", "UFPI", "UGI", "UNFI", "UNM", "UPBD",
    "URBN", "USLM", "VCYT", "VG", "VIAV", "VIR", "VIRT", "VLY", "VNO", "VNT",
    "VNTR", "VOYA", "VRNS", "VSH", "VSSH", "VSTO", "WAL", "WBS", "WCC", "WD",
    "WDFC", "WEN", "WERN", "WEX", "WH", "WHD", "WHR", "WING", "WK", "WLK",
    "WMK", "WMS", "WOR", "WPC", "WSFS", "WSM", "WSO", "WST", "WTFC", "WTRG",
    "WTS", "WU", "WWD", "WWE", "X", "XNCR", "XPO", "XPRO", "YETI", "ZI",
    "ZION", "ZWS",
]

# ═══════════════════════════════════════════════════════════════════════════════
# S&P 600 - SMALL CAP (~600 stocks)
# ═══════════════════════════════════════════════════════════════════════════════

SP600_SMALLCAP = [
    "AAOI", "AAXN", "ABCB", "ABEO", "ABG", "ABM", "ABTX", "ACAD", "ACCO", "ACEL",
    "ACET", "ACLS", "ACNB", "ACRE", "ACTG", "ACV", "ADMA", "ADUS", "AEGN", "AEIS",
    "AEMD", "AERI", "AEY", "AFGE", "AGIO", "AGYS", "AHCO", "AHH", "AIMC", "AIN",
    "AIR", "AIRC", "AIT", "AJRD", "AKR", "ALCO", "ALEX", "ALGT", "ALKS", "ALRM",
    "ALRS", "ALTG", "ALV", "ALVR", "AMAG", "AMBA", "AMBC", "AMBP", "AMC", "AMEH",
    "AMSF", "AMWD", "ANAB", "ANDE", "ANF", "ANGI", "ANIK", "ANIP", "AOSL", "APEI",
    "APG", "APOG", "APPN", "APPF", "APPS", "APTS", "ARGO", "ARKO", "ARL", "ARNC",
    "AROC", "ARRY", "ARTNA", "ASGN", "ASIX", "ASPS", "ASTE", "ASUR", "ATEN", "ATEX",
    "ATGE", "ATHM", "ATKR", "ATNI", "ATOM", "ATRA", "ATRC", "ATRO", "ATSG", "ATXI",
    "AUB", "AUDC", "AVAV", "AVID", "AVNS", "AVNT", "AVT", "AWRE", "AXGN", "AXLA",
    "AXNX", "AXSM", "AYLA", "AZZ", "B", "BALY", "BANC", "BAND", "BANF", "BANR",
    "BASE", "BATRA", "BATRK", "BBBY", "BBCP", "BBDC", "BBIO", "BBSI", "BCBP", "BCC",
    "BCDA", "BCE", "BCH", "BCML", "BCOV", "BCRX", "BCYC", "BDGE", "BDN", "BELFB",
    "BGCP", "BGS", "BGSF", "BHB", "BHE", "BHLB", "BIG", "BJRI", "BKD", "BKE",
    "BKEP", "BKH", "BKU", "BL", "BLBD", "BLDR", "BLFS", "BLKB", "BLMN", "BLNK",
    "BLUE", "BLVD", "BMA", "BMCH", "BMLP", "BMRC", "BMRN", "BMTC", "BNED", "BNFT",
    "BNL", "BOCH", "BODY", "BOH", "BOKF", "BOLT", "BOOM", "BOOT", "BPFH", "BPMC",
    "BPOP", "BPRN", "BRC", "BREW", "BRG", "BRID", "BRKL", "BRKS", "BRP", "BRT",
    "BSIG", "BSM", "BSRR", "BSVN", "BTAI", "BTU", "BUSE", "BV", "BWFG", "BWL-A",
    "BWXT", "BXC", "BXMT", "BY", "BYD", "BYSI", "BZFD", "CABA", "CAC", "CACI",
    "CADE", "CAKE", "CAL", "CALB", "CALM", "CAMP", "CARA", "CARE", "CARG", "CARV",
    "CASA", "CASH", "CASI", "CASS", "CATC", "CATO", "CATY", "CBAN", "CBAY", "CBB",
    "CBNK", "CBRL", "CBSH", "CBT", "CBU", "CBZ", "CCAP", "CCBG", "CCNE", "CCOI",
    "CCSI", "CDEV", "CDK", "CDMO", "CDNA", "CDR", "CDTX", "CDXC", "CDZI", "CECO",
    "CELC", "CEIX", "CENT", "CENTA", "CENX", "CEQP", "CERS", "CEVA", "CFB", "CFFI",
    "CFFN", "CFR", "CFRX", "CFX", "CGBD", "CGEM", "CGI", "CHCI", "CHCO", "CHCT",
    "CHDN", "CHEF", "CHGG", "CHH", "CHMI", "CHMG", "CHRD", "CHRW", "CHS", "CHUY",
    "CHWY", "CIM", "CINF", "CIVB", "CIX", "CJJD", "CKPT", "CKX", "CLAR", "CLBK",
    "CLCT", "CLDX", "CLH", "CLNE", "CLPR", "CLPT", "CLW", "CLXT", "CMBM", "CMC",
    "CMCL", "CMCO", "CMCSA", "CMD", "CMO", "CMP", "CMPO", "CMPR", "CMRX", "CMTL",
    "CNCE", "CNDT", "CNMD", "CNNX", "CNOB", "CNO", "CNS", "CNX", "COGT", "COHU",
    "COKE", "COLB", "COLD", "COLL", "COLM", "COMM", "CONE", "CONN", "COOP", "CORE",
    "CORR", "CORT", "COST", "COTY", "COUP", "COWN", "CPAC", "CPE", "CPF", "CPG",
    "CPK", "CPLP", "CPRI", "CPRT", "CPSI", "CPSS", "CRAI", "CRDF", "CREE", "CRGY",
    "CRI", "CRIS", "CRK", "CRMD", "CRMT", "CRNC", "CRNX", "CROX", "CRS", "CRUS",
    "CRVL", "CRVS", "CRWS", "CRXT", "CSFL", "CSGS", "CSII", "CSIQ", "CSL", "CSOD",
    "CSTL", "CSTM", "CSV", "CSWI", "CTBI", "CTKB", "CTLP", "CTO", "CTRE", "CTRN",
    "CTS", "CTXR", "CUBE", "CUBI", "CUE", "CURI", "CUZ", "CVA", "CVBF", "CVCO",
    "CVCY", "CVGI", "CVGW", "CVLG", "CVLT", "CVM", "CVNA", "CVRX", "CVV", "CW",
    "CWCO", "CWEN", "CWH", "CWST", "CWT", "CXW", "CYBR", "CYDE", "CYRX",
]

# ═══════════════════════════════════════════════════════════════════════════════
# RUSSELL 2000 ADDITIONS - MICRO & SMALL CAP (~800 more stocks)
# ═══════════════════════════════════════════════════════════════════════════════

RUSSELL_2000_ADDITIONS = [
    # A
    "AADI", "AAIC", "AAMC", "AAME", "AAPB", "AAWW", "ABCL", "ABIO", "ABLV", "ABNB",
    "ABOS", "ABST", "ABUS", "ACAD", "ACAH", "ACAN", "ACAQ", "ACCD", "ACEL", "ACER",
    "ACET", "ACHC", "ACHR", "ACIU", "ACLE", "ACLS", "ACMR", "ACNB", "ACOR", "ACRS",
    "ACRX", "ACST", "ACTG", "ACVA", "ADAP", "ADBE", "ADEA", "ADER", "ADGI", "ADIL",
    "ADMA", "ADMP", "ADMS", "ADN", "ADNW", "ADOC", "ADS", "ADSE", "ADSK", "ADT",
    "ADTX", "ADUS", "ADV", "ADVM", "ADXN", "AEAE", "AEHR", "AEIS", "AELA", "AENZ",
    "AERI", "AESE", "AEY", "AFAR", "AFB", "AFC", "AFCG", "AFFY", "AFGE", "AFI",
    "AFIB", "AFMD", "AFRI", "AFRM", "AFYA", "AGBA", "AGCO", "AGE", "AGEN", "AGFS",
    "AGFY", "AGIO", "AGLE", "AGM", "AGNC", "AGRI", "AGRO", "AGRX", "AGS", "AGTI",
    "AGYS", "AHCO", "AHG", "AHH", "AHI", "AHPI", "AHR", "AHT", "AI", "AIB",
    "AIC", "AIF", "AIHS", "AIMD", "AIOT", "AIRC", "AIRG", "AIRI", "AIRS", "AIT",
    "AIU", "AIV", "AIVI", "AIZ", "AJRD", "AJX", "AKAM", "AKAN", "AKBA", "AKLI",
    "AKR", "AKRO", "AKTS", "AKTX", "AKU", "AKUS", "AKYA", "ALAR", "ALBT", "ALCC",
    "ALCO", "ALDX", "ALEC", "ALEX", "ALFI", "ALG", "ALGM", "ALGN", "ALGS", "ALGT",
    "ALHC", "ALIM", "ALIT", "ALJJ", "ALK", "ALKS", "ALKT", "ALL", "ALLE", "ALLG",
    "ALLK", "ALLO", "ALLT", "ALLY", "ALNY", "ALOR", "ALOT", "ALPP", "ALRM", "ALRN",
    "ALRS", "ALSA", "ALSN", "ALT", "ALTG", "ALTI", "ALTO", "ALTR", "ALTU", "ALTV",
    "ALV", "ALVO", "ALVR", "ALXO", "ALYA", "ALZN", "AM", "AMAG", "AMAL", "AMAT",
    "AMBA", "AMBC", "AMBO", "AMBP", "AMC", "AMCR", "AMCX", "AMD", "AME", "AMED",
    "AMEH", "AMG", "AMGN", "AMH", "AMHC", "AMK", "AMKR", "AMLX", "AMN", "AMNB",
    "AMOT", "AMP", "AMPE", "AMPG", "AMPH", "AMPL", "AMPY", "AMR", "AMRC", "AMRK",
    "AMRN", "AMRS", "AMRX", "AMS", "AMSC", "AMSF", "AMST", "AMSWA", "AMT", "AMTB",
    "AMTI", "AMTX", "AMWD", "AMWL", "AMX", "AMYT", "AMZN", "AN", "ANAB", "ANDE",
    "ANF", "ANGH", "ANGI", "ANGN", "ANGO", "ANIK", "ANIP", "ANIX", "ANNX", "ANPC",
    "ANSS", "ANTE", "ANTX", "ANVS", "ANY", "AOSL", "AORT", "AOS", "AOSL", "AOUT",
    "AP", "APA", "APAM", "APCA", "APCX", "APD", "APDN", "APEI", "APEN", "APGE",
    "APG", "APGN", "APH", "API", "APLD", "APLE", "APLS", "APLT", "APM", "APMI",
    "APN", "APO", "APOG", "APP", "APPF", "APPN", "APPS", "APRE", "APRN", "APTI",
    "APTS", "APTV", "APTX", "APVO", "APWC", "APXI", "APYX", "AQB", "AQMS", "AQN",
    "AQST", "AQU", "AR", "ARAV", "ARAY", "ARBE", "ARC", "ARCB", "ARCC", "ARCE",
    "ARCH", "ARCO", "ARCT", "ARDS", "ARDX", "ARE", "AREB", "AREC", "ARES", "ARGU",
    "ARGX", "ARHS", "ARI", "ARIA", "ARIS", "ARIZ", "ARKO", "ARKR", "ARL", "ARLO",
    "ARLP", "ARMK", "ARMP", "ARNC", "AROC", "AROW", "ARQQ", "ARQT", "ARR", "ARRW",
    "ARRY", "ARTE", "ARTL", "ARTNA", "ARTW", "ARVL", "ARVN", "ARW", "ARWR", "ARYA",
    "ARZZ", "AS", "ASA", "ASAI", "ASAN", "ASBFY", "ASB", "ASCA", "ASGN", "ASH",
    "ASIX", "ASLE", "ASLN", "ASM", "ASMB", "ASML", "ASND", "ASO", "ASPA", "ASPN",
    "ASPS", "ASPU", "ASRT", "ASRV", "ASTE", "ASTS", "ASUR", "ASX", "ATAI", "ATAT",
    "ATCX", "ATEC", "ATEK", "ATEN", "ATEX", "ATFV", "ATGE", "ATHA", "ATHE", "ATHM",
    "ATHX", "ATI", "ATIF", "ATIP", "ATKR", "ATLC", "ATLO", "ATMC", "ATMV", "ATMU",
    "ATNF", "ATNI", "ATNM", "ATNX", "ATO", "ATOM", "ATOS", "ATR", "ATRA", "ATRC",
    "ATRI", "ATRO", "ATRS", "ATSG", "ATUS", "ATVI", "ATXG", "ATXI", "ATXS", "AU",
    
    # B-D
    "BBAI", "BBCP", "BBDC", "BBIG", "BBIO", "BBLG", "BBSI", "BCAB", "BCBP", "BCDA",
    "BCEL", "BCLI", "BCML", "BCOV", "BCRX", "BCYC", "BDTX", "BEAM", "BEAT", "BECN",
    "BEKE", "BELFA", "BFAM", "BFLY", "BFRI", "BGCP", "BGFV", "BGNE", "BGSF", "BHIL",
    "BHVN", "BIGC", "BILL", "BIMI", "BIOL", "BIOR", "BIRD", "BKCC", "BKEP", "BKSY",
    "BKTI", "BLBD", "BLBX", "BLCO", "BLDP", "BLDR", "BLFS", "BLIN", "BLMN", "BLND",
    "BLNK", "BLRX", "BLUE", "BMBL", "BMEA", "BNED", "BNGO", "BNOX", "BNRG", "BNTC",
    "BNTX", "BOIL", "BOOM", "BORR", "BOWL", "BOXD", "BPMC", "BPOP", "BPRN", "BRAG",
    "BRBR", "BRBS", "BRDG", "BRDS", "BREZ", "BRID", "BRKL", "BRLT", "BROS", "BRSP",
    "BRY", "BSFC", "BSIG", "BSMX", "BSRR", "BSVN", "BTAI", "BTBD", "BTCM", "BTCS",
    "BTG", "BTMD", "BTRS", "BTWN", "BUSE", "BVFL", "BWAQ", "BWMN", "BWXT", "BYFC",
    "BYRN", "BYSI", "BZFD", "BZUN", "CAAS", "CABA", "CALM", "CAMP", "CARA", "CARE",
    "CARG", "CARS", "CART", "CARV", "CASA", "CASH", "CASI", "CASS", "CATO", "CAVA",
    "CBAT", "CBAN", "CBAY", "CBNK", "CBRL", "CBSH", "CBST", "CBUS", "CCBG", "CCEL",
    "CCEP", "CCIX", "CCLD", "CCNE", "CCRD", "CCRN", "CCSI", "CCXI", "CDAY", "CDEV",
    "CDK", "CDLX", "CDMO", "CDNA", "CDNS", "CDTX", "CDXC", "CDXS", "CDZI", "CECO",
    "CELH", "CELU", "CENQ", "CENTA", "CEPU", "CEQP", "CERE", "CERS", "CERT", "CEVA",
    "CFBK", "CFFI", "CFFN", "CFLT", "CFRX", "CGAU", "CGBD", "CGEM", "CGEN", "CGNT",
    "CGTX", "CHCI", "CHCO", "CHCT", "CHEF", "CHGG", "CHKP", "CHMI", "CHMG", "CHNG",
    "CHNR", "CHPT", "CHRS", "CHSCP", "CHTR", "CHUY", "CHWY", "CIAN", "CIEN", "CIFR",
    "CINC", "CIVB", "CIXX", "CIZN", "CKPT", "CLAR", "CLBK", "CLBR", "CLBT", "CLCT",
    "CLDX", "CLEU", "CLFD", "CLGN", "CLIR", "CLMT", "CLNE", "CLNN", "CLNX", "CLOV",
    "CLPR", "CLPS", "CLPT", "CLRB", "CLRO", "CLSK", "CLST", "CLTL", "CLVR", "CLVS",
    "CLXT", "CMAX", "CMCL", "CMCO", "CMCSA", "CME", "CMLS", "CMMB", "CMPO", "CMPR",
    "CMPS", "CMRA", "CMRX", "CMTG", "CMTL", "CNCE", "CNDA", "CNDT", "CNET", "CNFR",
    "CNMD", "CNNB", "CNNE", "CNOB", "CNSL", "CNSP", "CNTA", "CNTB", "CNTG", "CNTY",
    "CNXC", "CNXN", "COCP", "CODA", "CODX", "COEP", "COGT", "COHU", "COIN", "COKE",
    "COLB", "COLL", "COMM", "COMP", "CONE", "CONN", "COOK", "COOL", "COOP", "COPX",
    "CORT", "COSM", "COST", "COUP", "COUR", "COYA", "COYA", "CPHC", "CPIX", "CPNG",
    "CPRI", "CPSH", "CPSS", "CPTN", "CRAI", "CRBP", "CRBU", "CRCT", "CRDF", "CRDL",
    "CRDO", "CREG", "CREX", "CRGE", "CRGO", "CRGY", "CRIS", "CRMD", "CRMT", "CRNC",
    "CRNT", "CRNX", "CRON", "CROX", "CRSP", "CRSR", "CRTD", "CRTX", "CRUS", "CRVL",
    "CRVS", "CRWD", "CRWS", "CRXT", "CRYO", "CSCO", "CSGP", "CSGS", "CSII", "CSIQ",
    "CSOD", "CSTE", "CSTL", "CSTM", "CSTR", "CSWC", "CTAQ", "CTBI", "CTCX", "CTHR",
    "CTKB", "CTLP", "CTMX", "CTOS", "CTRA", "CTRE", "CTRM", "CTRN", "CTSH", "CTSO",
    "CTXR", "CUBA", "CUBB", "CUBE", "CUBI", "CUEN", "CUE", "CURI", "CURV", "CUTR",
    "CVAC", "CVBF", "CVCO", "CVCY", "CVEO", "CVGI", "CVGW", "CVKD", "CVLG", "CVLT",
    "CVLY", "CVM", "CVNA", "CVRX", "CVV", "CWBC", "CWBR", "CWCO", "CWEN", "CWST",
    "CXAI", "CXDO", "CXSE", "CXSW", "CYAN", "CYBR", "CYCC", "CYCN", "CYDY", "CYMI",
    "CYRN", "CYRX", "CYTH", "CYTK", "CZFS", "CZNC", "CZOO", "CZR", "CZWI", "DADA",
    "DAIO", "DAKT", "DARE", "DASH", "DATS", "DAVA", "DAVE", "DAWN", "DBGI", "DBRG",
    "DBVT", "DCBO", "DCFC", "DCGO", "DCP", "DCPH", "DCUE", "DDI", "DDL", "DDMX",
    "DDS", "DECA", "DECK", "DENN", "DERM", "DFLI", "DFPH", "DFS", "DGHI", "DGIC",
    "DGII", "DGLY", "DH", "DHCA", "DHC", "DHHC", "DHIL", "DHT", "DHX", "DIBS",
    "DIN", "DINO", "DIOD", "DIST", "DJCO", "DK", "DKNG", "DLO", "DLPN", "DLTH",
    "DLTR", "DM", "DMAC", "DMK", "DMRC", "DMTK", "DMYY", "DNA", "DNLI", "DNMR",
    "DNUT", "DNOW", "DNUT", "DOC", "DOCN", "DOCS", "DOCU", "DOGZ", "DOMO", "DOOO",
    "DORM", "DOV", "DOXI", "DPZ", "DRCT", "DRH", "DRIO", "DRM", "DRMA", "DRRX",
    "DRS", "DRTS", "DRVN", "DSGN", "DSGX", "DSKE", "DSKY", "DSP", "DSPG", "DSS",
    "DSX", "DTC", "DTCK", "DTE", "DTF", "DTI", "DTIL", "DTRT", "DTSS", "DUET",
    "DUK", "DUOT", "DUOL", "DVAL", "DVAX", "DVN", "DWG", "DWSN", "DXC", "DXCM",
    "DXF", "DXLG", "DXPE", "DXR", "DXYN", "DYAI", "DYFN", "DYN", "DYNT", "DZSI",
    
    # E-H
    "EA", "EAC", "EAD", "EAF", "EAR", "EARN", "EAT", "EB", "EBET", "EBIX",
    "EBMT", "EBON", "EBS", "EBTC", "ECC", "ECDA", "ECF", "ECHO", "ECOL", "ECOR",
    "ECPG", "ECX", "EDAP", "EDBL", "EDD", "EDIT", "EDRY", "EDSA", "EDTK", "EDTX",
    "EDUC", "EEA", "EEFT", "EEIQ", "EFBI", "EFOI", "EFSC", "EFSH", "EG", "EGAN",
    "EGBN", "EGF", "EGHT", "EGIO", "EGLY", "EGO", "EGRX", "EGY", "EH", "EHC",
    "EHTH", "EIC", "EIGR", "ELAN", "ELB", "ELEV", "ELF", "ELLO", "ELME", "ELON",
    "ELP", "ELS", "ELTK", "ELUT", "ELVA", "ELVT", "ELYM", "ELY", "EM", "EMBC",
    "EMCG", "EME", "EMKR", "EML", "EMLD", "EMLP", "EMMA", "EMMF", "EMXC", "ENCP",
    "ENDP", "ENER", "ENG", "ENIC", "ENO", "ENOB", "ENOV", "ENPC", "ENPH", "ENR",
    "ENS", "ENSC", "ENSG", "ENSV", "ENT", "ENTA", "ENTG", "ENTO", "ENTX", "ENV",
    "ENVA", "ENVB", "ENVX", "ENZ", "EOCW", "EOG", "EOLS", "EOSE", "EPAC", "EPAM",
    "EPC", "EPIX", "EPM", "EPOW", "EPR", "EPRT", "EPSN", "EQ", "EQBK", "EQC",
    "EQD", "EQHA", "EQH", "EQIX", "EQNR", "EQR", "EQRX", "EQS", "EQT", "EQWL",
    "EQX", "ERAS", "ERC", "ERES", "ERIC", "ERIE", "ERII", "ERNA", "ERO", "ERYP",
    "ES", "ESAB", "ESCA", "ESCR", "ESEA", "ESGA", "ESGR", "ESGU", "ESI", "ESLT",
    "ESMI", "ESMT", "ESNT", "ESP", "ESPR", "ESQ", "ESRT", "ESS", "ESSA", "ESTA",
    "ESTE", "ESXB", "ET", "ETAC", "ETB", "ETD", "ETNB", "ETON", "ETR", "ETRN",
    "ETSY", "ETWO", "EU", "EUDA", "EURN", "EVA", "EVAX", "EVBN", "EVBG", "EVC",
    "EVCM", "EVE", "EVER", "EVEX", "EVFM", "EVG", "EVGN", "EVGO", "EVGR", "EVH",
    "EVI", "EVLV", "EVMV", "EVO", "EVOA", "EVOK", "EVOP", "EVR", "EVRG", "EVRI",
    "EVT", "EVTC", "EVTL", "EVTV", "EW", "EWBC", "EWCZ", "EXAI", "EXAS", "EXC",
    "EXEL", "EXFY", "EXG", "EXGP", "EXK", "EXLS", "EXOC", "EXP", "EXPD", "EXPE",
    "EXPI", "EXPO", "EXPR", "EXTR", "EYE", "EYEN", "EYEP", "EYES", "EYPT",
    
    "FA", "FAF", "FAMI", "FANG", "FARM", "FARO", "FATH", "FATP", "FAX", "FBC",
    "FBHS", "FBIO", "FBIZ", "FBK", "FBMS", "FBNC", "FBP", "FBRT", "FC", "FCAP",
    "FCBC", "FCCO", "FCEL", "FCF", "FCFS", "FCN", "FCNCA", "FCPT", "FCUV", "FDBC",
    "FDMT", "FDP", "FDS", "FDUS", "FDX", "FE", "FELE", "FEMY", "FENC", "FENG",
    "FENY", "FER", "FERG", "FET", "FFBC", "FFBW", "FFC", "FFG", "FFIC", "FFIE",
    "FFIN", "FFIV", "FFNW", "FFWM", "FGBI", "FGEN", "FGF", "FGL", "FGMC", "FGNA",
    "FHB", "FHI", "FHLC", "FHN", "FHTX", "FI", "FIBI", "FIBK", "FICO", "FIGS",
    "FINM", "FINV", "FINW", "FIP", "FISI", "FITB", "FIV", "FIVE", "FIVN", "FIX",
    "FIXX", "FIZZ", "FKWL", "FL", "FLAG", "FLAQU", "FLG", "FLGC", "FLIC", "FLIR",
    "FLJ", "FLL", "FLME", "FLNG", "FLNK", "FLNT", "FLO", "FLR", "FLS", "FLSW",
    "FLT", "FLUX", "FLWS", "FLXS", "FLYW", "FMAO", "FMBH", "FMBI", "FMC", "FMNB",
    "FMN", "FMS", "FMTX", "FMX", "FMY", "FN", "FNA", "FNB", "FNCB", "FNCH",
    "FND", "FNDA", "FNDC", "FNDX", "FNHC", "FNKO", "FNLC", "FNV", "FNWB", "FNWD",
    "FOA", "FOE", "FOLD", "FONR", "FOR", "FORD", "FORG", "FORM", "FORR", "FORTY",
    "FOSL", "FOSLL", "FOUR", "FOX", "FOXA", "FOXF", "FPAY", "FPH", "FPI", "FPRX",
    "FPXE", "FR", "FRA", "FRAF", "FRBA", "FRBK", "FRC", "FRD", "FREE", "FREEW",
    "FREQ", "FREY", "FRG", "FRGE", "FRGI", "FRGT", "FRHC", "FRLN", "FRME", "FROG",
    "FRPH", "FRPT", "FRSH", "FRST", "FRSX", "FRT", "FRXB", "FRZA", "FSBC", "FSBW",
    "FSCO", "FSD", "FSFG", "FSK", "FSKR", "FSLY", "FSM", "FSNB", "FSP", "FSRN",
    "FSS", "FSTR", "FSV", "FTAI", "FTCH", "FTCI", "FTDR", "FTEK", "FTFT", "FTHM",
    "FTII", "FTK", "FTNT", "FTPA", "FTR", "FTRP", "FTS", "FTSI", "FUBO", "FUL",
    "FULC", "FULT", "FUN", "FUNC", "FUND", "FURY", "FUSB", "FUSN", "FUTU", "FUV",
    "FVAM", "FVCB", "FVRR", "FWAC", "FWBI", "FWP", "FWRD", "FWRG", "FXNC", "FYBR",
    
    "GAIA", "GAIN", "GALT", "GAMB", "GAMC", "GAN", "GANX", "GAQ", "GASS", "GATE",
    "GATO", "GAU", "GAZA", "GB", "GBBK", "GBCI", "GBDC", "GBLI", "GBNH", "GBNY",
    "GBR", "GBS", "GBT", "GCAP", "GCI", "GCMG", "GCO", "GCT", "GCTK", "GCV",
    "GDDY", "GDEN", "GDEV", "GDL", "GDNR", "GDRX", "GDS", "GDST", "GDTC", "GDV",
    "GDYN", "GE", "GECC", "GEF", "GEGA", "GEHC", "GEL", "GEN", "GENC", "GENE",
    "GENI", "GENK", "GEO", "GEOS", "GERN", "GES", "GET", "GETY", "GEVO", "GFAI",
    "GFF", "GFGF", "GFLU", "GFL", "GFOR", "GFS", "GGAL", "GGB", "GGE", "GGII",
    "GGN", "GGR", "GGVE", "GH", "GHIX", "GHLD", "GHL", "GHM", "GHY", "GIAC",
    "GIB", "GIFI", "GIGM", "GIII", "GILD", "GILT", "GIM", "GIS", "GIW", "GKOS",
    "GL", "GLAQU", "GLAD", "GLBE", "GLBS", "GLBZ", "GLDD", "GLDG", "GLDI", "GLEE",
    "GLG", "GLHA", "GLIA", "GLLI", "GLMD", "GLNG", "GLO", "GLOB", "GLOP", "GLP",
    "GLPG", "GLPI", "GLRE", "GLRI", "GLSI", "GLST", "GLTO", "GLT", "GLUE", "GLUU",
    "GLW", "GLYC", "GM", "GMAB", "GMBL", "GMDA", "GME", "GMED", "GMFI", "GMGI",
    "GMTX", "GNE", "GNFT", "GNK", "GNL", "GNLN", "GNMK", "GNPX", "GNRC", "GNRS",
    "GNS", "GNSS", "GNTX", "GNTY", "GNUS", "GNW", "GO", "GOBI", "GOCO", "GODN",
    "GOEV", "GOGL", "GOGN", "GOGO", "GOLD", "GOLF", "GOOD", "GOODN", "GOOG", "GOOGL",
    "GOOS", "GORO", "GORV", "GOSS", "GOVX", "GP", "GPC", "GPCO", "GPI", "GPK",
    "GPMT", "GPN", "GPOR", "GPRE", "GPRO", "GPS", "GRBK", "GRC", "GRCY", "GRFS",
    "GRIN", "GRMN", "GRNA", "GRNB", "GRND", "GRNQ", "GRNT", "GRNV", "GROM", "GROV",
    "GROW", "GRP", "GRPN", "GRRR", "GRSH", "GRTS", "GRTX", "GRVY", "GRWG", "GS",
    "GSAQ", "GSBC", "GSAT", "GSBD", "GSC", "GSCW", "GSEV", "GShK", "GSIT", "GSK",
    "GSL", "GSM", "GSMG", "GSS", "GSUM", "GSUN", "GT", "GTBP", "GTE", "GTEC",
    "GTES", "GTH", "GTHX", "GTI", "GTIM", "GTLB", "GTLS", "GTN", "GTX", "GTY",
    "GTYH", "GUNR", "GUT", "GUTS", "GV", "GVA", "GVP", "GWAV", "GWGH", "GWII",
    "GWRE", "GWRS", "GWW", "GXO", "GXXI", "GYE", "H", "HA", "HABT", "HACK",
    "HAFC", "HAIN", "HAL", "HALL", "HALO", "HAO", "HAPP", "HARP", "HAS", "HAUZ",
    "HAYN", "HBAN", "HBCP", "HBI", "HBIO", "HBM", "HBNC", "HBP", "HBT", "HCA",
    "HCAR", "HCAT", "HCC", "HCCI", "HCI", "HCIC", "HCKT", "HCM", "HCNWF", "HCSG",
    "HCTI", "HCVI", "HCWB", "HD", "HDGE", "HDL", "HDMV", "HDNG", "HE", "HEAR",
    "HEES", "HEINY", "HELE", "HEP", "HEPA", "HEPS", "HES", "HESM", "HEXO", "HFFG",
    "HFRO", "HFWA", "HGH", "HGLB", "HGSH", "HGV", "HHC", "HHGC", "HHH", "HHLA",
    "HHS", "HI", "HIBB", "HIE", "HIFS", "HIG", "HIHO", "HII", "HIL", "HILO",
    "HIMS", "HIMX", "HIO", "HIPO", "HITI", "HIVE", "HIW", "HLF", "HLI", "HLIT",
    "HLLY", "HLMN", "HLN", "HLNE", "HLT", "HLVX", "HLX", "HM", "HMA", "HMC",
    "HMCO", "HMLP", "HMN", "HMNF", "HMPT", "HMST", "HMTV", "HMY", "HNDL", "HNNA",
    "HNRG", "HNST", "HNVR", "HOG", "HOLI", "HOLO", "HOLX", "HOMB", "HOME", "HON",
    "HONE", "HOOD", "HOOK", "HOPE", "HOTH", "HOUR", "HOUS", "HOV", "HOVNP", "HP",
    "HPCO", "HPE", "HPK", "HPP", "HPQ", "HPS", "HQH", "HQL", "HQY", "HR",
    "HRB", "HRC", "HRMY", "HRTG", "HRTX", "HRZN", "HSAI", "HSBC", "HSC", "HSDT",
    "HSIC", "HSII", "HSKA", "HSON", "HST", "HSTM", "HSUR", "HSY", "HT", "HTA",
    "HTBI", "HTBK", "HTCR", "HTD", "HTFC", "HTGC", "HTH", "HTHT", "HTIA", "HTLD",
    "HTLF", "HTOO", "HTY", "HTZ", "HUBB", "HUBG", "HUBS", "HUD", "HUDI", "HUM",
    "HUMV", "HUNO", "HURC", "HURN", "HUSA", "HUT", "HUYA", "HVBC", "HVT", "HWBK",
    "HWC", "HWKN", "HWM", "HXL", "HY", "HYAC", "HYGH", "HYLN", "HYMB", "HYRE",
    "HYTR", "HYUP", "HYW", "HZN", "HZNP", "HZO",
    
    # I-L
    "IAC", "IAE", "IAF", "IAG", "IART", "IAS", "IBCP", "IBEX", "IBIO", "IBKR",
    "IBM", "IBN", "IBOC", "IBP", "IBRX", "IBTX", "IBUY", "ICAD", "ICAGY", "ICAR",
    "ICE", "ICFI", "ICHR", "ICLR", "ICMB", "ICNC", "ICON", "ICPT", "ICUI", "ICVX",
    "ID", "IDA", "IDAI", "IDBA", "IDCC", "IDEV", "IDEX", "IDN", "IDOG", "IDRA",
    "IDRV", "IDT", "IDXX", "IDYA", "IE", "IEA", "IEC", "IEHC", "IEP", "IESC",
    "IEX", "IFIN", "IFN", "IFS", "IFRX", "IGA", "IGAC", "IGIC", "IGMS", "IGR",
    "IGTA", "IGT", "IGTB", "IH", "IHD", "IHG", "IHIT", "IHT", "IHTA", "III",
    "IIIN", "IIIV", "IIM", "IINN", "IIVI", "IJJP", "IKT", "ILMN", "ILPT", "IMAB",
    "IMAC", "IMAX", "IMBI", "IMCC", "IMCR", "IMGN", "IMGO", "IMKTA", "IMMP", "IMMR",
    "IMNM", "IMO", "IMOM", "IMOS", "IMPL", "IMPX", "IMRN", "IMRX", "IMTE", "IMTX",
    "IMUX", "IMVT", "IMXI", "INAB", "INAQ", "INBK", "INBKZ", "INBS", "INCR", "INCY",
    "INDB", "INDI", "INDO", "INDT", "INDY", "INFA", "INFN", "INFO", "INFU", "INFY",
    "ING", "INGN", "INGR", "INH", "INHD", "INKA", "INKY", "INM", "INMB", "INMD",
    "INN", "INNV", "INO", "INOD", "INPX", "INRT", "INSE", "INSG", "INSM", "INSP",
    "INST", "INSW", "INT", "INTA", "INTC", "INTE", "INTG", "INTR", "INTU", "INTZ",
    "INUV", "INVA", "INVE", "INVH", "INVO", "INVZ", "INZY", "IO", "IOAC", "IONM",
    "IONQ", "IONS", "IOVA", "IP", "IPA", "IPAR", "IPAX", "IPDN", "IPG", "IPHA",
    "IPHI", "IPI", "IPOD", "IPOF", "IPSC", "IPVF", "IPW", "IQ", "IQLT", "IQMD",
    "IQNT", "IQV", "IR", "IRBT", "IRCP", "IRDM", "IRET", "IRFC", "IRIX", "IRM",
    "IRMD", "IRNT", "IRON", "IROQ", "IRRX", "IRS", "IRT", "IRTC", "IRWD", "ISAA",
    "ISBC", "ISCO", "ISDR", "ISEE", "ISIG", "ISNS", "ISO", "ISPC", "ISPR", "ISRG",
    "ISSC", "ISSI", "ISTR", "ISUN", "IT", "ITAQ", "ITCB", "ITCI", "ITGR", "ITI",
    "ITIC", "ITOS", "ITP", "ITRG", "ITRI", "ITRM", "ITRN", "ITT", "ITUB", "ITW",
    "IVA", "IVAC", "IVAN", "IVC", "IVDA", "IVDN", "IVES", "IVLU", "IVR", "IVVD",
    "IVZ", "IX", "IXAQ", "IXHL", "IZEA", "J", "JACK", "JACO", "JAGX", "JAKK",
    "JAM", "JAN", "JAZZ", "JBGS", "JBHT", "JBI", "JBL", "JBLU", "JBSS", "JBT",
    "JCE", "JCI", "JCOM", "JCO", "JCS", "JD", "JE", "JEF", "JELD", "JEQ",
    "JFIN", "JFR", "JG", "JGCD", "JGGCF", "JHAA", "JHG", "JHI", "JHS", "JHX",
    "JILL", "JJSF", "JKS", "JLL", "JMIA", "JMPN", "JNJ", "JNPR", "JO", "JOBY",
    "JOE", "JOUT", "JOY", "JP", "JPFA", "JPM", "JQUA", "JRO", "JRS", "JRSH",
    "JRVR", "JS", "JSM", "JSPR", "JTAI", "JTPY", "JUP", "JVA", "JVAL", "JW-A",
    "JWN", "JWSM", "JYAC", "JYNT", "JZ", "JZXN", "K", "KACL", "KALA", "KALU",
    "KAMN", "KAR", "KARO", "KAVL", "KB", "KBE", "KBH", "KBR", "KBWB", "KCGI",
    "KCNY", "KDLY", "KDMN", "KDP", "KE", "KELYA", "KEN", "KEP", "KEQU", "KERN",
    "KERU", "KEY", "KEYS", "KFFB", "KFRC", "KFS", "KFY", "KG", "KGC", "KGEI",
    "KHC", "KIDS", "KIM", "KIN", "KINS", "KINZ", "KIO", "KIRK", "KIRO", "KITT",
    "KKR", "KL", "KLAC", "KLDW", "KLIC", "KLRB", "KLTR", "KLXE", "KMB", "KMI",
    "KMPH", "KMPR", "KMT", "KMX", "KN", "KNBE", "KNF", "KNOP", "KNSA", "KNSL",
    "KNTE", "KNTK", "KNX", "KO", "KOD", "KODK", "KOF", "KOLD", "KONE", "KOOL",
    "KOP", "KOPN", "KORE", "KOS", "KOSS", "KPTI", "KRBP", "KREF", "KRG", "KRKR",
    "KRMD", "KRNL", "KRNY", "KRON", "KROS", "KRP", "KRTX", "KRUS", "KRYS", "KSCP",
    "KSPN", "KSS", "KSTS", "KT", "KTB", "KTOS", "KTTA", "KUKE", "KULR", "KURA",
    "KVHI", "KVSA", "KVUE", "KW", "KWIK", "KWWEB", "KWR", "KXIN", "KYCH", "KYMR",
    "KZIA", "KZR",
    
    "LAB", "LABP", "LAC", "LACQ", "LAD", "LADR", "LAKE", "LAMR", "LANC", "LAND",
    "LANDO", "LARK", "LASR", "LATN", "LAUR", "LAWS", "LAZ", "LAZR", "LBC", "LBPH",
    "LBRDA", "LBRDK", "LBRDP", "LBRT", "LBTYA", "LBTYK", "LC", "LCAHU", "LCID",
    "LCII", "LCNB", "LCUT", "LDHA", "LDHAU", "LDI", "LDP", "LDOS", "LDS", "LE",
    "LEA", "LEAF", "LEAS", "LECO", "LEDS", "LEE", "LEG", "LEGN", "LEJU", "LEN",
    "LEO", "LESL", "LEU", "LEV", "LEVI", "LFAC", "LFC", "LFG", "LFLY", "LFMD",
    "LFST", "LFT", "LFUS", "LFVN", "LGFA", "LGFB", "LGI", "LGIH", "LGND", "LGTH",
    "LGTO", "LGVC", "LGVN", "LH", "LHCG", "LHX", "LI", "LIFE", "LIFW", "LII",
    "LILA", "LILAK", "LILM", "LIN", "LINC", "LIND", "LINE", "LINK", "LION", "LIQT",
    "LITE", "LITM", "LIVB", "LIVE", "LIVN", "LIVX", "LIXT", "LIZY", "LIZI", "LJAQ",
    "LKCO", "LKFN", "LKQ", "LL", "LLAP", "LLNW", "LLY", "LMAT", "LMB", "LMBS",
    "LMDX", "LMFA", "LMND", "LMNR", "LMNX", "LMOS", "LMT", "LNC", "LND", "LNDC",
    "LNG", "LNKB", "LNSR", "LNT", "LNTH", "LNW", "LOAN", "LOB", "LOCO", "LODE",
    "LOGC", "LOGI", "LOOP", "LOPE", "LORL", "LOSA", "LOVE", "LOW", "LPCN", "LPG",
    "LPI", "LPLA", "LPRO", "LPSN", "LPTH", "LPTX", "LPX", "LQDA", "LQDT", "LRCX",
    "LRFC", "LRMR", "LRND", "LRN", "LSAF", "LSBK", "LSCC", "LSF", "LSI", "LSPD",
    "LSPR", "LSTR", "LSXMA", "LSXMB", "LSXMK", "LTBR", "LTC", "LTCH", "LTH", "LTHM",
    "LTRPA", "LTRPB", "LTRX", "LTRY", "LU", "LULU", "LUMN", "LUMO", "LUNA", "LUNG",
    "LUNR", "LUV", "LUXA", "LUXH", "LVHD", "LVLU", "LVO", "LVOX", "LVRA", "LVS",
    "LVTX", "LVWR", "LW", "LWAY", "LWLG", "LX", "LXEH", "LXFR", "LXP", "LXRX",
    "LXSW", "LXU", "LYB", "LYEL", "LYFT", "LYG", "LYRA", "LYTS", "LYV", "LZ",
    "LZBY", "LZM",
]

# M-Z Additional Small/Micro Caps
RUSSELL_2000_MZ = [
    # M
    "MA", "MAA", "MAAQ", "MAC", "MACA", "MACK", "MACU", "MAG", "MAIA", "MAIN",
    "MAMS", "MANH", "MANT", "MANU", "MAPS", "MAR", "MARA", "MARK", "MARPS", "MAS",
    "MASI", "MASS", "MAT", "MATH", "MATV", "MATW", "MATX", "MAX", "MAXN", "MAXR",
    "MAYS", "MBAV", "MBCN", "MBI", "MBII", "MBIN", "MBIO", "MBIT", "MBNK", "MBRX",
    "MBSC", "MBUU", "MBWM", "MC", "MCAA", "MCAC", "MCAD", "MCAE", "MCAG", "MCB",
    "MCBC", "MCBS", "MCD", "MCDR", "MCFE", "MCFT", "MCG", "MCHP", "MCHX", "MCI",
    "MCK", "MCN", "MCO", "MCR", "MCRB", "MCRI", "MCS", "MCTX", "MCW", "MCY",
    "MD", "MDCA", "MDCP", "MDGL", "MDGS", "MDIA", "MDJH", "MDLA", "MDLZ", "MDMN",
    "MDNA", "MDRX", "MDS", "MDT", "MDU", "MDVX", "MDWT", "MDXG", "MDXH", "ME",
    "MEC", "MED", "MEDS", "MEDP", "MEGL", "MEIP", "MELI", "MEOH", "MER", "MERC",
    "MESA", "MESO", "MET", "META", "METC", "MEXX", "MF", "MFA", "MFAC", "MFC",
    "MFD", "MFG", "MFGP", "MFH", "MFIC", "MFIN", "MFM", "MFV", "MG", "MGA",
    "MGAM", "MGC", "MGEE", "MGF", "MGI", "MGIC", "MGLD", "MGM", "MGNI", "MGNX",
    "MGP", "MGPI", "MGR", "MGRB", "MGRM", "MGTA", "MGTX", "MGU", "MGY", "MH",
    "MHD", "MHF", "MHH", "MHI", "MHK", "MHLA", "MHLD", "MHN", "MHNC", "MHO",
    "MHRA", "MHY", "MI", "MICS", "MID", "MIDD", "MIGI", "MILE", "MIMO", "MIN",
    "MIND", "MINM", "MIRO", "MIRM", "MIST", "MIT", "MITK", "MITT", "MIXT", "MIY",
    "MKC", "MKD", "MKL", "MKSI", "MKTW", "MKTX", "ML", "MLAB", "MLAI", "MLCO",
    "MLDP", "MLEC", "MLGO", "MLI", "MLKN", "MLM", "MLNK", "MLP", "MLR", "MLSS",
    "MLTX", "MLYS", "MMAC", "MMC", "MMEX", "MMI", "MMLP", "MMM", "MMMB", "MMS",
    "MMSI", "MMT", "MMU", "MMX", "MMYT", "MN", "MNCL", "MNDO", "MNDT", "MNDY",
    "MNET", "MNKD", "MNMD", "MNOV", "MNP", "MNPR", "MNR", "MNRL", "MNRO", "MNSO",
    "MNST", "MNSB", "MNTK", "MNTN", "MNTS", "MNTX", "MO", "MOB", "MOBL", "MOD",
    "MODN", "MOFG", "MOGO", "MOH", "MOHR", "MOJO", "MOL", "MOLD", "MOMO", "MON",
    "MONS", "MOOD", "MOON", "MOR", "MORF", "MORN", "MORRB", "MOS", "MOTS", "MOV",
    "MOVE", "MOVN", "MP", "MPA", "MPAA", "MPAC", "MPB", "MPC", "MPLX", "MPLN",
    "MPLX", "MPQ", "MPRA", "MPTI", "MPV", "MPW", "MPWR", "MPX", "MQ", "MQT",
    "MQY", "MR", "MRAM", "MRBK", "MRCC", "MRCY", "MRDB", "MREO", "MRIN", "MRK",
    "MRKR", "MRM", "MRNA", "MRNS", "MRO", "MRTN", "MRTX", "MRUS", "MRVI", "MRVL",
    "MS", "MSA", "MSB", "MSBI", "MSBK", "MSCI", "MSD", "MSEX", "MSFT", "MSGE",
    "MSGM", "MSGS", "MSI", "MSM", "MSN", "MSON", "MSP", "MSPR", "MSS", "MSSA",
    "MSTZ", "MSY", "MT", "MTA", "MTAC", "MTAQ", "MTB", "MTC", "MTCH", "MTD",
    "MTDR", "MTEK", "MTEM", "MTEN", "MTEX", "MTG", "MTH", "MTLS", "MTN", "MTNB",
    "MTOR", "MTP", "MTR", "MTRN", "MTRX", "MTRY", "MTSI", "MTTR", "MTUS", "MTW",
    "MTX", "MTY", "MTZ", "MU", "MUDS", "MUI", "MUJ", "MULG", "MUN", "MURF",
    "MURA", "MUSA", "MUSK", "MUX", "MVBF", "MVF", "MVIS", "MVO", "MVRS", "MVST",
    "MVSY", "MVT", "MWA", "MWG", "MX", "MXC", "MXCT", "MXE", "MXF", "MXIM",
    "MXL", "MYD", "MYE", "MYFW", "MYGN", "MYMD", "MYN", "MYNA", "MYO", "MYOV",
    "MYPS", "MYRG", "MYTE",
    
    # N
    "NAC", "NAD", "NAFC", "NAHD", "NAIL", "NAK", "NAMS", "NAN", "NAOV", "NAPA",
    "NARI", "NAT", "NATH", "NATI", "NATR", "NAV", "NAVB", "NAVG", "NAVI", "NAVNF",
    "NAZ", "NB", "NBAR", "NBEV", "NBHC", "NBIX", "NBK", "NBN", "NBRV", "NBSE",
    "NBST", "NBTB", "NBTX", "NBXG", "NBY", "NC", "NCA", "NCAC", "NCAM", "NCLH",
    "NCMI", "NCNA", "NCNO", "NCPL", "NCR", "NCRA", "NCTY", "NCVI", "NCV", "NCVI",
    "NDAC", "NDLS", "NDMO", "NDSN", "NE", "NEA", "NEAR", "NEBB", "NECB", "NEE",
    "NEGG", "NEGG", "NEL", "NEM", "NEO", "NEOG", "NEON", "NEOV", "NEP", "NEPH",
    "NEPT", "NERV", "NESR", "NET", "NETI", "NEU", "NEW", "NEWA", "NEWP", "NEWR",
    "NEWS", "NEWT", "NEXT", "NFBK", "NFE", "NFGC", "NFJ", "NFLT", "NFYS", "NG",
    "NGAC", "NGD", "NGG", "NGL", "NGMS", "NGS", "NGVC", "NGVT", "NH", "NHC",
    "NHI", "NHIC", "NHTC", "NI", "NICK", "NINE", "NIO", "NIOBF", "NIR", "NISN",
    "NITB", "NIU", "NJR", "NK", "NKLA", "NKSH", "NKTR", "NKTX", "NL", "NLSN",
    "NLS", "NLSP", "NLTX", "NLY", "NM", "NMCO", "NMFC", "NMG", "NMHI", "NMIH",
    "NMK", "NMM", "NMR", "NMRD", "NMRK", "NMTR", "NMTX", "NNA", "NNAG", "NNAVF",
    "NNBR", "NNDM", "NNE", "NNI", "NNN", "NNOX", "NNP", "NNRX", "NNY", "NOA",
    "NOAH", "NOBL", "NOC", "NODK", "NOG", "NOK", "NOMD", "NOON", "NOR", "NOTV",
    "NOV", "NOVA", "NOVB", "NOVN", "NOVT", "NOWAR", "NOW", "NPA", "NPK", "NPO",
    "NPTN", "NPV", "NQP", "NR", "NRAC", "NRBO", "NRC", "NRDS", "NREF", "NRG",
    "NRGV", "NRGX", "NRIM", "NRIX", "NRK", "NRO", "NRP", "NRSN", "NRT", "NRXP",
    "NRXS", "NS", "NSA", "NSC", "NSCO", "NSEC", "NSH", "NSIT", "NSL", "NSP",
    "NSPR", "NSR", "NSSC", "NSTB", "NSTD", "NSTE", "NSTG", "NSYS", "NTAP", "NTCT",
    "NTGN", "NTIC", "NTLA", "NTNX", "NTR", "NTRA", "NTRB", "NTRI", "NTRP", "NTRS",
    "NTSO", "NTSPR", "NTST", "NTWK", "NU", "NUE", "NULC", "NUM", "NUMI", "NUO",
    "NURO", "NUS", "NUTX", "NUV", "NUVB", "NUW", "NUWE", "NVA", "NVAC", "NVAX",
    "NVCN", "NVCR", "NVCT", "NVDA", "NVEC", "NVEE", "NVEI", "NVFY", "NVG", "NVGS",
    "NVIR", "NVIV", "NVMI", "NVNO", "NVO", "NVOS", "NVR", "NVRO", "NVS", "NVSA",
    "NVST", "NVT", "NVTA", "NVTAQ", "NVTS", "NVUS", "NVVE", "NVVEW", "NVX", "NWBI",
    "NWE", "NWFL", "NWG", "NWGL", "NWL", "NWLI", "NWN", "NWPX", "NWS", "NWSA",
    "NWTG", "NX", "NXC", "NXDT", "NXE", "NXGN", "NXMH", "NXN", "NXP", "NXPI",
    "NXPL", "NXRT", "NXST", "NXTC", "NXTD", "NXTP", "NYC", "NYCB", "NYF", "NYMB",
    "NYMTI", "NYMTN", "NYMTO", "NYMTZ", "NYT", "NYXH",
    
    # O-P
    "O", "OAC", "OABI", "OAK", "OAKC", "OAKS", "OAM", "OAS", "OASMF", "OB",
    "OBCI", "OBK", "OBLG", "OBNK", "OBSV", "OBT", "OCA", "OCC", "OCCI", "OCFC",
    "OCFT", "OCFTP", "OCGN", "OCN", "OCSL", "OCUL", "OCUP", "OCX", "ODC", "ODFL",
    "ODP", "ODT", "ODV", "OEC", "OEG", "OESX", "OFC", "OFFS", "OFG", "OFIX",
    "OFP", "OFS", "OFSS", "OGE", "OGEN", "OGI", "OGN", "OGS", "OHAI", "OHI",
    "OI", "OIA", "OIBR", "OII", "OIL", "OILK", "OIS", "OKE", "OKTA", "OKYO",
    "OLA", "OLED", "OLK", "OLLI", "OLMA", "OLN", "OLO", "OLP", "OLPX", "OM",
    "OMAB", "OMC", "OMCC", "OMCL", "OMEG", "OMER", "OMEX", "OMF", "OMGA", "OMH",
    "OMI", "OMIC", "OMIH", "OMNI", "OMNIQ", "OMQ", "ON", "ONB", "ONBP", "ONCR",
    "ONCS", "ONCT", "ONDK", "ONE", "ONEW", "ONDS", "ONEM", "ONEW", "ONFO", "ONGP",
    "ONIT", "ONL", "ONMD", "ONNE", "ONON", "ONST", "ONTO", "ONTX", "ONYX", "OOMA",
    "OP", "OPA", "OPAD", "OPBK", "OPCH", "OPDN", "OPEN", "OPFI", "OPGN", "OPHT",
    "OPI", "OPIN", "OPINL", "OPIR", "OPK", "OPLA", "OPLG", "OPNT", "OPOF", "OPRA",
    "OPRT", "OPRX", "OPS", "OPTN", "OPTT", "OPTY", "OPVS", "OPY", "ORA", "ORAL",
    "ORC", "ORCH", "ORCC", "ORCL", "ORGN", "ORGO", "ORGS", "ORI", "ORIC", "ORLA",
    "ORLY", "ORMP", "ORN", "ORNBF", "ORNY", "ORPH", "ORRF", "ORTX", "OSBC", "OSBK",
    "OSBS", "OSG", "OSH", "OSI", "OSIS", "OSK", "OSPN", "OSRV", "OSS", "OSSY",
    "OST", "OSTK", "OSUR", "OSW", "OTEX", "OTHR", "OTIS", "OTLK", "OTLY", "OTMOA",
    "OTR", "OTRA", "OTRK", "OTRKP", "OTTR", "OUST", "OUT", "OUTR", "OUTW", "OVBC",
    "OVID", "OVLY", "OVV", "OWL", "OWLT", "OXM", "OXMR", "OXSQ", "OXUS", "OXY",
    "OZ", "OZON", "OZSC",
    
    "PAAS", "PAC", "PACA", "PACB", "PACK", "PACS", "PACW", "PACX", "PAG", "PAGP",
    "PAGS", "PAHY", "PAHC", "PAI", "PALIH", "PALT", "PAM", "PANL", "PANS", "PANW",
    "PAR", "PARA", "PARF", "PARQ", "PARR", "PASK", "PASS", "PASG", "PATH", "PATK",
    "PAVM", "PAVMW", "PAVMZ", "PAVS", "PAX", "PAYX", "PB", "PBA", "PBAX", "PBBK",
    "PBD", "PBF", "PBFS", "PBFX", "PBH", "PBHC", "PBIA", "PBM", "PBPB", "PBR",
    "PBS", "PBT", "PBW", "PBYI", "PCAR", "PCB", "PCBK", "PCB", "PCC", "PCCT",
    "PCCW", "PCD", "PCEF", "PCG", "PCGU", "PCH", "PCI", "PCIN", "PCK", "PCM",
    "PCN", "PCOM", "PCOR", "PCPC", "PCQ", "PCRX", "PCSA", "PCTI", "PCTTU", "PCTY",
    "PCVX", "PCY", "PCYC", "PCYG", "PCYO", "PD", "PDAC", "PDCE", "PDCO", "PDD",
    "PDE", "PDEX", "PDFS", "PDGI", "PDLB", "PDM", "PDO", "PDP", "PDRC", "PDS",
    "PDSB", "PDT", "PE", "PEAK", "PEB", "PEBK", "PEBO", "PECA", "PECO", "PED",
    "PEER", "PEG", "PEGA", "PEGB", "PEI", "PEJ", "PEJO", "PEKA", "PEN", "PENN",
    "PEO", "PEP", "PEPH", "PEPPR", "PERE", "PERI", "PERMA", "PESI", "PET", "PETQ",
    "PETS", "PETZ", "PETV", "PEVI", "PEV", "PEX", "PEY", "PEZ", "PF", "PFC",
    "PFBC", "PFD", "PFDR", "PFE", "PFES", "PFF", "PFFD", "PFG", "PFGC", "PFH",
    "PFHD", "PFI", "PFIE", "PFIN", "PFIS", "PFL", "PFLT", "PFMT", "PFN", "PFO",
    "PFPT", "PFS", "PFSW", "PFTA", "PFUT", "PFX", "PG", "PGAL", "PGC", "PGEMBF",
    "PGJ", "PGLC", "PGNY", "PGP", "PGR", "PGRM", "PGRN", "PGRS", "PGRW", "PGTI",
    "PGUL", "PGY", "PGZ", "PH", "PHALF", "PHARMA", "PHAS", "PHBI", "PHD", "PHDG",
    "PHDN", "PHG", "PHGE", "PHHM", "PHIC", "PHII", "PHIO", "PHK", "PHLT", "PHM",
    "PHMB", "PHO", "PHR", "PHT", "PHUN", "PHUNW", "PHX", "PHYA", "PHYS", "PHYT",
    "PI", "PIA", "PIAI", "PICC", "PICK", "PICO", "PID", "PIE", "PIEI", "PIEQ",
    "PIFS", "PIIG", "PII", "PIM", "PIMZ", "PIN", "PINC", "PINE", "PINN", "PINS",
    "PIO", "PIOE", "PIPB", "PIPC", "PIPH", "PIPR", "PIRS", "PISH", "PISU", "PIT",
    "PITA", "PITR", "PIV", "PIY", "PIZ", "PJH", "PJT", "PK", "PKB", "PKBK",
    "PKE", "PKG", "PKI", "PKOH", "PKW", "PKX", "PL", "PLAB", "PLAO", "PLAV",
    "PLAYA", "PLBC", "PLBY", "PLCE", "PLD", "PLDG", "PLG", "PLIN", "PLL", "PLM",
    "PLMI", "PLMJ", "PLMR", "PLNHF", "PLNT", "PLOW", "PLPC", "PLRB", "PLRX", "PLSE",
    "PLSQ", "PLTG", "PLTK", "PLTR", "PLTY", "PLUG", "PLUS", "PLUR", "PLVN", "PLW",
    "PLX", "PLXP", "PLXS", "PLYA", "PLYM", "PM", "PMBC", "PMC", "PMCB", "PMD",
    "PME", "PMF", "PML", "PMM", "PMN", "PMNT", "PMO", "PMOM", "PMP", "PMTG",
    "PMTS", "PMX", "PNBK", "PNC", "PNF", "PNFP", "PNFPP", "PNI", "PNM", "PNNR",
    "PNNT", "PNQI", "PNR", "PNRA", "PNRG", "PNSR", "PNST", "PNT", "PNTG", "PNTM",
    "PNW", "PNXP", "POAI", "POCI", "PODD", "POET", "POGR", "POLA", "POLL", "POLO",
    "POLY", "POM", "POND", "POOL", "POPE", "POR", "PORK", "PORT", "POS", "POSH",
    "POST", "POT", "POTI", "POTX", "POWR", "POWRU", "PP", "PPBI", "PPBT", "PPC",
    "PPD", "PPG", "PPGH", "PPH", "PPI", "PPHP", "PPIH", "PPL", "PPLN", "PPSI",
    "PPT", "PPTA", "PQ", "PQG", "PQIN", "PR", "PRA", "PRAA", "PRAX", "PRB",
    "PRCH", "PRCP", "PRCT", "PRDA", "PRDS", "PRDO", "PRE", "PREF", "PRFT", "PRG",
    "PRGA", "PRGO", "PRGS", "PRGX", "PRI", "PRID", "PRII", "PRIM", "PRIV", "PRK",
    "PRLB", "PRLD", "PRLX", "PRM", "PRMB", "PRME", "PRMP", "PRMW", "PRN", "PRNT",
    "PRNT", "PRO", "PROC", "PROF", "PROG", "PROK", "PROV", "PROX", "PRPH", "PRPL",
    "PRPO", "PRQR", "PRS", "PRSI", "PRSP", "PRSR", "PRSW", "PRT", "PRTC", "PRTH",
    "PRTK", "PRTS", "PRTY", "PRUC", "PRUF", "PRVB", "PRVL", "PRVR", "PRWB", "PRX",
    "PS", "PSA", "PSAC", "PSAR", "PSBC", "PSBQ", "PSC", "PSCC", "PSCD", "PSCE",
    "PSCF", "PSCH", "PSCI", "PSCL", "PSCT", "PSCU", "PSDN", "PSEC", "PSET", "PSF",
    "PSHG", "PSI", "PSIX", "PSL", "PSM", "PSMC", "PSN", "PSNH", "PSNL", "PSO",
    "PSON", "PSOS", "PSPIX", "PSQ", "PSQI", "PSQM", "PSR", "PSTG", "PSTI", "PSTL",
    "PSTV", "PSTX", "PSX", "PSXP", "PT", "PTA", "PTAI", "PTAU", "PTC", "PTCT",
    "PTE", "PTEN", "PTGX", "PTHR", "PTI", "PTIC", "PTIV", "PTLO", "PTM", "PTMN",
    "PTN", "PTO", "PTON", "PTR", "PTRA", "PTRS", "PTS", "PTSI", "PTSN", "PTVE",
    "PTWN", "PTY", "PTYX", "PUBM", "PUCK", "PUK", "PULM", "PULS", "PUMP", "PUODW",
    "PURE", "PURI", "PURN", "PVBC", "PVH", "PVHO", "PVL", "PVQY", "PWFL", "PWM",
    "PWOD", "PWP", "PWR", "PWSC", "PWUO", "PX", "PXD", "PXDT", "PXI", "PXJ",
    "PXLW", "PXMD", "PXS", "PXSAP", "PXSAV", "PYACU", "PYAW", "PYDS", "PYN", "PYPD",
    "PYPL", "PYR", "PYS", "PYXS", "PYZ", "PZZA", "PZZA",
    
    # Q-R
    "Q", "QAT", "QBTS", "QC", "QCLN", "QCOM", "QCRH", "QD", "QDEL", "QDF",
    "QDIV", "QDOC", "QEH", "QFIN", "QGEN", "QGLUE", "QH", "QHLT", "QID", "QK",
    "QKLS", "QLI", "QLGN", "QLIK", "QLM", "QLTA", "QLYS", "QMCO", "QNBC", "QNCX",
    "QNGY", "QNST", "QNXN", "QPAT", "QPM", "QPRO", "QQQJ", "QQQM", "QQQN", "QQY",
    "QRAFT", "QRDO", "QRPQ", "QRVO", "QS", "QSG", "QSI", "QSIAQ", "QSR", "QSTOR",
    "QTI", "QTNT", "QTOO", "QTRH", "QTRS", "QTUM", "QTWN", "QTWO", "QUAI", "QUAQU",
    "QUBT", "QUCM", "QUIK", "QUMU", "QURE", "QVCC", "QXRH", "QYLD", "QYLG",
    
    "R", "RAAS", "RAAN", "RACE", "RAD", "RADI", "RADX", "RAIL", "RAIN", "RAM",
    "RAMDA", "RAMP", "RANI", "RAPT", "RARE", "RAVE", "RAVN", "RBA", "RBAC", "RBAR",
    "RBAX", "RBBN", "RBCAA", "RBCP", "RBCN", "RBFL", "RBI", "RBKB", "RBNB", "RBND",
    "RBOT", "RBS", "RBSH", "RBTI", "RBTX", "RBUS", "RBZ", "RC", "RCAP", "RCBP",
    "RCC", "RCEL", "RCES", "RCFA", "RCF", "RCFP", "RCG", "RCII", "RCKT", "RCKY",
    "RCL", "RCM", "RCMT", "RCNB", "RCON", "RCPI", "RCRT", "RCRTW", "RCS", "RCUS",
    "RDCM", "RDFN", "RDHL", "RDI", "RDIB", "RDII", "RDIVU", "RDIV", "RDN", "RDNT",
    "RDS", "RDUS", "RDW", "RDWR", "RDY", "RE", "REAL", "REAX", "REB", "REBN",
    "REBS", "RECT", "REE", "REED", "REEN", "REFR", "REG", "REGN", "REGI", "REGL",
    "REIT", "RELL", "RELV", "RELX", "RELY", "RENE", "RENEW", "RENN", "RENO", "RENT",
    "REOR", "REPL", "REPX", "RER", "RERE", "RES", "RESH", "RESN", "RETA", "RETC",
    "RETO", "REVA", "REV", "REVB", "REVG", "REVH", "REVI", "REVS", "REW", "REX",
    "REXN", "REXR", "REZI", "RF", "RFAC", "RFDI", "RFG", "RFIL", "RFL", "RFM",
    "RFMD", "RFP", "RFR", "RFRPQ", "RFS", "RGA", "RGCO", "RGEN", "RGLD", "RGLS",
    "RGNX", "RGP", "RGR", "RGRDX", "RGS", "RGTI", "RGTIW", "RGU", "RH", "RHC",
    "RHE", "RHEL", "RHI", "RHIM", "RHK", "RHL", "RHMD", "RHNB", "RHP", "RICK",
    "RIDE", "RIG", "RIGL", "RILY", "RILYL", "RILYN", "RILYO", "RILYP", "RILYZ",
    "RIO", "RIOT", "RISN", "RIV", "RIVN", "RIVR", "RIVS", "RIXT", "RJF", "RKD",
    "RKT", "RKTA", "RKTB", "RL", "RLAY", "RLEA", "RLGT", "RLI", "RLIMQ", "RLJ",
    "RLK", "RLMD", "RLN", "RLRN", "RLX", "RM", "RMAX", "RMB", "RMBI", "RMBL",
    "RMBS", "RMCF", "RMD", "RMFS", "RMI", "RMII", "RMIII", "RMIX", "RMM", "RMNI",
    "RMO", "RMON", "RMR", "RMRD", "RMRK", "RMT", "RMTI", "RNAC", "RNAM", "RNDB",
    "RNDY", "RNER", "RNEW", "RNG", "RNGR", "RNIT", "RNLX", "RNMD", "RNNB", "RNP",
    "RNR", "RNRG", "RNS", "RNST", "RNWK", "ROAM", "ROBO", "ROBT", "ROC", "ROCB",
    "ROCK", "ROCL", "ROD", "RODE", "RODI", "ROGEN", "ROIC", "ROJI", "ROKU", "ROL",
    "ROMA", "ROMT", "ROOF", "ROOT", "ROP", "ROSE", "ROSG", "ROSS", "ROST", "ROTH",
    "ROUS", "ROVR", "RPAY", "RPD", "RPID", "RPLA", "RPLO", "RPM", "RPMB", "RPMT",
    "RPRX", "RPTX", "RPV", "RQI", "RRAC", "RRBAQ", "RRBAW", "RRBI", "RRC", "RRCB",
    "RRDS", "RRHRS", "RRR", "RRSTI", "RRX", "RS", "RSF", "RSG", "RSI", "RSKD",
    "RSLS", "RSPR", "RSVAU", "RSVU", "RSVX", "RTAH", "RTIX", "RTLR", "RTM", "RTNB",
    "RTO", "RTPH", "RTRX", "RTX", "RUBY", "RUK", "RUM", "RUNB", "RUNH", "RUNI",
    "RUN", "RUSHA", "RUSHB", "RUTH", "RVAC", "RVER", "RVES", "RVF", "RVFF", "RVLC",
    "RVLP", "RVLT", "RVLV", "RVLV", "RVMD", "RVNC", "RVNU", "RVP", "RVPH", "RVSB",
    "RVT", "RWAV", "RWL", "RWLK", "RWOD", "RWT", "RXDX", "RXL", "RXN", "RXRA",
    "RXRAU", "RXST", "RY", "RYAAY", "RYAM", "RYAN", "RYB", "RYDE", "RYI", "RYN",
    "RYPLN", "RYPR", "RYTM",
    
    # S-Z
    "S", "SA", "SAB", "SABR", "SACC", "SAFE", "SAGA", "SAGE", "SAH", "SAIA",
    "SAIC", "SAIL", "SAJ", "SAL", "SALM", "SALT", "SAM", "SAMAW", "SAMG", "SAN",
    "SANB", "SAND", "SANG", "SANM", "SANP", "SANO", "SAP", "SAR", "SARA", "SASI",
    "SASR", "SAT", "SATL", "SATO", "SATS", "SATX", "SAV", "SAVE", "SAY", "SB",
    "SBAC", "SBBA", "SBBP", "SBC", "SBCF", "SBCP", "SBCW", "SBEA", "SBEV", "SBFG",
    "SBFM", "SBGI", "SBH", "SBHC", "SBI", "SBIG", "SBII", "SBIMF", "SBLK", "SBMF",
    "SBNA", "SBNC", "SBNY", "SBOW", "SBR", "SBRA", "SBS", "SBSI", "SBSP", "SBT",
    "SBTX", "SBUX", "SBUX", "SBY", "SCCO", "SCEY", "SCHB", "SCHC", "SCHD", "SCHE",
    "SCHF", "SCHG", "SCHH", "SCHJ", "SCHK", "SCHL", "SCHM", "SCHN", "SCHO", "SCHP",
    "SCHR", "SCHT", "SCHU", "SCHV", "SCHW", "SCHX", "SCHZ", "SCI", "SCIF", "SCIS",
    "SCKT", "SCL", "SCLX", "SCM", "SCNI", "SCOO", "SCOR", "SCPE", "SCPH", "SCPL",
    "SCPS", "SCPU", "SCSC", "SCSR", "SCTL", "SCUI", "SCUR", "SCVL", "SCWO", "SCWX",
    "SCYX", "SD", "SDA", "SDAC", "SDCA", "SDCL", "SDC", "SDCY", "SDEI", "SDEX",
    "SDG", "SDGR", "SDH", "SDHY", "SDIG", "SDIV", "SDLA", "SDLC", "SDLP", "SDMN",
    "SDO", "SDOW", "SDP", "SDPI", "SDRB", "SDRL", "SDRV", "SDRY", "SDS", "SDST",
    "SDT", "SDUSQ", "SDY", "SE", "SEAC", "SEADW", "SEAS", "SEAT", "SEB", "SECO",
    "SECT", "SEDG", "SEE", "SEED", "SEEL", "SEIC", "SEII", "SEM", "SEMI", "SEMR",
    "SENEA", "SENEB", "SENS", "SEOO", "SEPZ", "SER", "SERA", "SERO", "SERV", "SES",
    "SF", "SFB", "SFBC", "SFBS", "SFE", "SFET", "SFFG", "SFG", "SFH", "SFHY",
    "SFIX", "SFL", "SFLM", "SFM", "SFNC", "SFRC", "SFS", "SFST", "SFT", "SFUN",
    "SFWL", "SG", "SGA", "SGBX", "SGC", "SGEN", "SGFY", "SGH", "SGHC", "SGHL",
    "SGI", "SGIC", "SGIP", "SGLC", "SGLDU", "SGMA", "SGMO", "SGMS", "SGMT", "SGNS",
    "SGOC", "SGOL", "SGOV", "SGPI", "SGRF", "SGRY", "SGU", "SHAK", "SHBK", "SHBI",
    "SHC", "SHCR", "SHCTF", "SHEL", "SHEN", "SHG", "SHGB", "SHI", "SHIP", "SHLS",
    "SHLX", "SHO", "SHOO", "SHOP", "SHOT", "SHOW", "SHR", "SHRS", "SHRV", "SHV",
    "SHW", "SHY", "SHYF", "SHYG", "SI", "SIBN", "SIC", "SID", "SIEB", "SIEN",
    "SIER", "SIF", "SIFY", "SIG", "SIGA", "SIGC", "SIGI", "SIGM", "SIGU", "SII",
    "SILC", "SILK", "SILO", "SILV", "SIM", "SIMO", "SIMP", "SINT", "SIOX", "SIR",
    "SIRE", "SIRI", "SIRS", "SISB", "SITE", "SITM", "SIVB", "SIX", "SJ", "SJB",
    "SJI", "SJIJ", "SJIM", "SJIV", "SJM", "SJNK", "SJR", "SJT", "SJW", "SK",
    "SKGR", "SKF", "SKFJ", "SKGR", "SKH", "SKIN", "SKLZ", "SKM", "SKP", "SKQI",
    "SKT", "SKWD", "SKWS", "SKX", "SKY", "SKYA", "SKYB", "SKYH", "SKYY", "SKYW",
    "SLAB", "SLAC", "SLAMU", "SLB", "SLBH", "SLCA", "SLDB", "SLDP", "SLE", "SLF",
    "SLG", "SLGC", "SLGL", "SLGN", "SLIM", "SLM", "SLMBP", "SLND", "SLNG", "SLNH",
    "SLNO", "SLP", "SLQT", "SLRB", "SLRC", "SLRN", "SLRX", "SLS", "SLSB", "SLT",
    "SLVR", "SLVS", "SLV", "SLVM", "SLVO", "SLVU", "SLVP", "SM", "SMACU", "SMAD",
    "SMAM", "SMAN", "SMAR", "SMBC", "SMBK", "SMBS", "SMC", "SMCI", "SMCP", "SME",
    "SMED", "SMFG", "SMFL", "SMFR", "SMG", "SMGI", "SMH", "SMHI", "SMHD", "SMID",
    "SMIH", "SMIT", "SMI", "SMJN", "SML", "SMLP", "SMLR", "SMM", "SMMCF", "SMMF",
    "SMMFG", "SMMU", "SMN", "SMOG", "SMOD", "SMP", "SMPC", "SMPL", "SMR", "SMRAT",
    "SMRT", "SMSI", "SMTA", "SMTC", "SMTI", "SMTS", "SMWB", "SNA", "SNAX", "SNBR",
    "SNC", "SNCE", "SNCR", "SNCY", "SND", "SNDA", "SNDE", "SNDK", "SNDL", "SNDQ",
    "SNDR", "SNDW", "SNDX", "SNE", "SNEX", "SNFCA", "SNGX", "SNHNU", "SNIIY", "SNL",
    "SNLN", "SNN", "SNNA", "SNOA", "SNOW", "SNP", "SNPO", "SNPR", "SNPS", "SNPT",
    "SNRG", "SNRH", "SNSE", "SNSR", "SNST", "SNT", "SNTG", "SNTI", "SNV", "SNX",
    "SNY", "SOBR", "SOCAU", "SOFI", "SOFO", "SOHU", "SOI", "SOJB", "SOJC", "SOJD",
    "SOL", "SOLE", "SOLF", "SOLO", "SOLS", "SOM", "SOMA", "SOME", "SOND", "SONN",
    "SONO", "SONX", "SONY", "SOO", "SOPH", "SOR", "SOROF", "SOS", "SOTK", "SOVO",
    "SOXL", "SOXQ", "SOXS", "SOXX", "SP", "SPAB", "SPACU", "SPAK", "SPAN", "SPAQ",
    "SPBC", "SPBO", "SPCB", "SPCF", "SPCE", "SPCH", "SPCI", "SPCX", "SPE", "SPEC",
    "SPEM", "SPEU", "SPEZ", "SPFF", "SPFI", "SPG", "SPGC", "SPGI", "SPGM", "SPGP",
    "SPGS", "SPH", "SPHB", "SPHD", "SPHY", "SPIB", "SPIC", "SPIR", "SPKE", "SPKL",
    "SPLB", "SPLG", "SPLK", "SPLP", "SPLV", "SPMB", "SPMD", "SPMV", "SPNE", "SPNG",
    "SPNS", "SPNT", "SPO", "SPOK", "SPOT", "SPON", "SPOU", "SPOW", "SPPI", "SPPN",
    "SPPP", "SPPR", "SPRB", "SPRC", "SPRG", "SPRO", "SPRQ", "SPRR", "SPRT", "SPRU",
    "SPRY", "SPSC", "SPSM", "SPSS", "SPT", "SPTB", "SPTK", "SPTL", "SPTM", "SPTN",
    "SPTS", "SPUC", "SPUN", "SPUX", "SPUS", "SPVC", "SPVU", "SPWH", "SPWR", "SPXB",
    "SPXC", "SPXL", "SPXN", "SPXS", "SPXT", "SPXU", "SPXV", "SPXX", "SPY", "SPYC",
    "SPYD", "SPYG", "SPYI", "SPYM", "SPYV", "SPYX", "SQ", "SQB", "SQBG", "SQFT",
    "SQLV", "SQM", "SQNS", "SQSP", "SQQQ", "SR", "SRAX", "SRC", "SRCE", "SRCL",
    "SRDX", "SRE", "SREA", "SRET", "SREV", "SRG", "SRGA", "SRI", "SRLP", "SRMX",
    "SRNE", "SROI", "SRPT", "SRRA", "SRRK", "SRS", "SRSA", "SRT", "SRTS", "SRTTY",
    "SRTY", "SRV", "SRVR", "SRZA", "SSAA", "SSAAU", "SSAB", "SSBK", "SSB", "SSBI",
    "SSBOX", "SSBP", "SSC", "SSCO", "SSD", "SSDW", "SSE", "SSEN", "SSER", "SSFI",
    "SSG", "SSGA", "SSGD", "SSHP", "SSI", "SSIC", "SSII", "SSIM", "SSIN", "SSJJ",
    "SSK", "SSL", "SSLJ", "SSLN", "SSLV", "SSLX", "SSM", "SSMK", "SSMS", "SSNT",
    "SSO", "SSP", "SSPK", "SSRM", "SSSS", "SSST", "SST", "SSTI", "SSTK", "SSTY",
    "SSU", "SSUS", "SSVK", "SSW", "SSWA", "SSWN", "SSWX", "SSY", "SSYS", "ST",
    "STAA", "STAB", "STAC", "STAF", "STAG", "STAM", "STAN", "STAR", "STBA", "STBX",
    "STC", "STCB", "STCH", "STCN", "STE", "STEL", "STEM", "STEP", "STER", "STFC",
    "STGN", "STGW", "STHRY", "STI", "STIC", "STIM", "STIO", "STIR", "STIX", "STK",
    "STKL", "STKRY", "STKS", "STLA", "STLD", "STM", "STMP", "STMR", "STN", "STNA",
    "STNC", "STNE", "STNG", "STNO", "STOK", "STON", "STOR", "STPC", "STPH", "STPK",
    "STPR", "STPS", "STR", "STRA", "STRC", "STRD", "STRE", "STRG", "STRM", "STRN",
    "STRO", "STRP", "STRS", "STRT", "STRW", "STRX", "STRY", "STT", "STTB", "STTC",
    "STTK", "STWO", "STWD", "STWHD", "STXB", "STXM", "STY", "STYE", "STYL", "STYLD",
    "STZ", "SU", "SUAC", "SUB", "SUBIQ", "SUBS", "SUCA", "SUDO", "SUI", "SUIC",
    "SUM", "SUMR", "SUMO", "SUMP", "SUN", "SUNA", "SUNL", "SUNN", "SUNS", "SUP",
    "SUPN", "SUPV", "SURE", "SURF", "SURG", "SUSB", "SUSC", "SUSL", "SUZ", "SV",
    "SVAM", "SVC", "SVIX", "SVJTY", "SVNA", "SVNX", "SVON", "SVR", "SVRA", "SVREW",
    "SVSFT", "SVSR", "SVT", "SVVC", "SVWM", "SVX", "SVXY", "SWAG", "SWAV", "SWBI",
    "SWCH", "SWI", "SWIM", "SWIR", "SWK", "SWKH", "SWKS", "SWM", "SWN", "SWP",
    "SWPP", "SWS", "SWTX", "SWX", "SWZ", "SXC", "SXCP", "SXI", "SXT", "SXTC",
    "SY", "SYBT", "SYBX", "SYF", "SYK", "SYKE", "SYM", "SYN", "SYNA", "SYNC",
    "SYND", "SYNE", "SYNL", "SYNNF", "SYPR", "SYRS", "SYT", "SYTA", "SYX", "SYY",
    "SZA", "SZC", "SZH", "SZHNU", "SZNE", "SZUL",
    
    # T-Z
    "T", "TA", "TAC", "TACO", "TACT", "TAK", "TAIT", "TAL", "TALK", "TALO",
    "TALS", "TAME", "TAN", "TANGO", "TANH", "TANK", "TANNI", "TANNL", "TANNZ", "TAO",
    "TAP", "TARA", "TARO", "TARS", "TAST", "TATT", "TAYD", "TBBK", "TBCP", "TBC",
    "TBIIF", "TBK", "TBLA", "TBLTF", "TBNK", "TBPH", "TC", "TCBC", "TCBI", "TCBIO",
    "TCBK", "TCBP", "TCBS", "TCCA", "TCD", "TCDA", "TCFCF", "TCFG", "TCFT", "TCGI",
    "TCH", "TCHC", "TCHF", "TCI", "TCMD", "TCNNF", "TCO", "TCOM", "TCON", "TCPC",
    "TCRT", "TCS", "TCVA", "TCX", "TD", "TDA", "TDAC", "TDBKU", "TDC", "TDE",
    "TDF", "TDG", "TDIV", "TDJ", "TDOC", "TDPAW", "TDS", "TDSB", "TDT", "TDTF",
    "TDTT", "TDV", "TDW", "TDY", "TE", "TEAM", "TECH", "TECK", "TECL", "TECS",
    "TEDU", "TEF", "TEI", "TEL", "TELA", "TELL", "TELNY", "TELS", "TENB", "TENX",
    "TEN", "TEO", "TER", "TERA", "TERM", "TERP", "TESS", "TETC", "TETE", "TETRA",
    "TEV", "TEVA", "TEX", "TFC", "TFCE", "TFCF", "TFI", "TFII", "TFIV", "TFLO",
    "TFLS", "TFLT", "TFX", "TG", "TGA", "TGAN", "TGB", "TGC", "TGEN", "TGGI",
    "TGH", "TGLS", "TGNA", "TGNT", "TGP", "TGRO", "TGS", "TGT", "TGTX", "TGX",
    "TH", "THAC", "THBR", "THC", "THCA", "THCB", "THCP", "THCT", "THCX", "THDN",
    "THEL", "THET", "THG", "THH", "THKK", "THMO", "THN", "THNA", "THO", "THOR",
    "THPS", "THQ", "THR", "THRD", "THRY", "THSN", "THTX", "THW", "TI", "TIAAU",
    "TIBR", "TIC", "TICS", "TIGO", "TIG", "TII", "TIKCF", "TILE", "TILL", "TIMB",
    "TIME", "TIO", "TIOA", "TIOB", "TIOAU", "TIOV", "TIP", "TISA", "TITN", "TIVA",
    "TIVIC", "TIXT", "TIXX", "TJX", "TK", "TKAT", "TKC", "TKLF", "TKR", "TKWY",
    "TL", "TLGA", "TLGGF", "TLGY", "TLIS", "TLMD", "TLMR", "TLN", "TLND", "TLNEF",
    "TLNT", "TLOFF", "TLP", "TLPH", "TLRO", "TLRY", "TLSA", "TLSRP", "TLT", "TLTE",
    "TLTF", "TLTH", "TLTP", "TLTR", "TLTS", "TLTW", "TLV", "TLVC", "TLYS", "TM",
    "TMAC", "TMAQ", "TMBR", "TMC", "TMCI", "TMCWF", "TMDI", "TMDX", "TMED", "TMFC",
    "TMF", "TMFB", "TMHC", "TMK", "TMKR", "TMLP", "TMO", "TMP", "TMPN", "TMPO",
    "TMPR", "TMPS", "TMPSY", "TMQ", "TMRA", "TMRG", "TMS", "TMSR", "TMSRQ", "TMST",
    "TMTC", "TMUS", "TMV", "TMVWY", "TMXN", "TN", "TNA", "TNAV", "TNC", "TNDM",
    "TNDR", "TNDX", "TNET", "TNFA", "TNFX", "TNGE", "TNI", "TNK", "TNL", "TNLK",
    "TNP", "TNRS", "TNTAQ", "TNTQ", "TNXP", "TO", "TOF", "TOIIW", "TOKE", "TOL",
    "TOLD", "TOMDF", "TONG", "TOON", "TOPS", "TOUR", "TOWN", "TOWR", "TPB", "TPC",
    "TPG", "TPGI", "TPGY", "TPH", "TPHS", "TPIC", "TPL", "TPLC", "TPLM", "TPNL",
    "TPR", "TPRE", "TPRM", "TPRT", "TPS", "TPST", "TPTX", "TPVG", "TPVY", "TPX",
    "TPZ", "TQQQ", "TR", "TRC", "TRCA", "TRCC", "TRCH", "TRDA", "TRE", "TREE",
    "TREM", "TREX", "TRGP", "TRH", "TRI", "TRIB", "TRIC", "TRIL", "TRIM", "TRIN",
    "TRIP", "TRIV", "TRIX", "TRKA", "TRKB", "TRKN", "TRLA", "TRMD", "TRMK", "TRMR",
    "TRN", "TRNA", "TRNC", "TRND", "TRNE", "TRNG", "TRNO", "TRNS", "TROG", "TRON",
    "TROP", "TROW", "TROX", "TRP", "TRPL", "TRPM", "TRPX", "TRQ", "TRR", "TRRI",
    "TRS", "TRSC", "TRST", "TRT", "TRTL", "TRTLU", "TRTN", "TRTX", "TRU", "TRUE",
    "TRUP", "TRUS", "TRUX", "TRV", "TRVG", "TRVN", "TRX", "TRXC", "TRXT", "TRZAF",
    "TS", "TSAT", "TSBK", "TSC", "TSCNF", "TSCPF", "TSCO", "TSCP", "TSCR", "TSE",
    "TSEM", "TSHA", "TSHP", "TSI", "TSIB", "TSIG", "TSLA", "TSLAQ", "TSLL", "TSLQ",
    "TSLR", "TSM", "TSMC", "TSN", "TSP", "TSPQ", "TSQ", "TSRI", "TST", "TSTS",
    "TSTV", "TT", "TTAC", "TTBK", "TTC", "TTCF", "TTCP", "TTCW", "TTD", "TTE",
    "TTEC", "TTEK", "TTFB", "TTFC", "TTFD", "TTFE", "TTFF", "TTGT", "TTGT", "TTI",
    "TTII", "TTMI", "TTNP", "TTON", "TTP", "TTSH", "TTSR", "TTSWQ", "TTTM", "TTTSF",
    "TTWO", "TU", "TUBA", "TUBE", "TUC", "TUES", "TUEM", "TUP", "TURN", "TUSA",
    "TUSK", "TUTR", "TUV", "TUYA", "TV", "TVAC", "TVAX", "TVC", "TVE", "TVGY",
    "TVIA", "TVIX", "TVK", "TVLLY", "TVPT", "TVTX", "TW", "TWA", "TWAM", "TWAR",
    "TWCB", "TWDL", "TWDLF", "TWDY", "TWI", "TWIN", "TWLO", "TWNK", "TWO", "TWOH",
    "TWOS", "TWOU", "TWST", "TWTR", "TX", "TXCE", "TXCR", "TXGE", "TXG", "TXHD",
    "TXI", "TXN", "TXNM", "TXPIU", "TXPL", "TXRH", "TXS", "TXT", "TXZU", "TY",
    "TYHT", "TYL", "TYME", "TYO", "TYPE", "TYRA", "TZA", "TZOO", "TZTOO",
    
    "U", "UA", "UAA", "UAL", "UAMY", "UAN", "UAVS", "UB", "UBA", "UBCP",
    "UBER", "UBFO", "UBK", "UBNK", "UBOH", "UBOH", "UBS", "UBSI", "UBX", "UCAR",
    "UCC", "UCBI", "UCBIO", "UCD", "UCF", "UCO", "UCS", "UCTI", "UCTT", "UDMY",
    "UDOW", "UDR", "UE", "UEC", "UEPS", "UEVM", "UF", "UFA", "UFAB", "UFI",
    "UFPI", "UFPT", "UFV", "UG", "UGA", "UGE", "UGI", "UGLD", "UGL", "UGP",
    "UHAL", "UHG", "UHS", "UHT", "UI", "UIHC", "UIS", "UIT", "UITYF", "UJB",
    "UK", "UKBK", "UL", "ULBI", "ULCC", "ULFI", "ULH", "ULTA", "ULTR", "ULY",
    "UM", "UMAC", "UMBF", "UMC", "UMH", "UMRX", "UNAM", "UNB", "UNCY", "UNFI",
    "UNG", "UNGS", "UNH", "UNIT", "UNL", "UNM", "UNMA", "UNP", "UNTY", "UNVR",
    "UONE", "UONEK", "UP", "UPBD", "UPC", "UPFN", "UPH", "UPHL", "UPLD", "UPP",
    "UPRO", "UPS", "UPST", "UPTD", "UPWK", "UPXI", "UPXY", "UQM", "UR", "URBN",
    "URGN", "URI", "URIG", "URM", "URSA", "URTX", "USA", "USAK", "USAP", "USAS",
    "USAT", "USB", "USBI", "USCB", "USCR", "USD", "USDU", "USEA", "USEG", "USEN",
    "USFD", "USG", "USGS", "USGU", "USHI", "USHY", "USIG", "USIO", "USLB", "USLM",
    "USMC", "USML", "USMV", "USNA", "USOI", "USOIL", "USP", "USPH", "USPU", "USR",
    "USRT", "USSM", "UST", "USTU", "USVN", "USVM", "USVP", "USWS", "USX", "USXF",
    "USZLY", "UT", "UTA", "UTAK", "UTC", "UTEF", "UTHR", "UTI", "UTL", "UTMD",
    "UTNF", "UTRS", "UTSL", "UTWO", "UTWY", "UTZ", "UU", "UUP", "UUUU", "UVE",
    "UVEE", "UVIX", "UVSP", "UVV", "UWHR", "UWMC", "UWN", "UXI", "UYC", "UYG",
    "UYM",
    
    "V", "VA", "VAC", "VACQU", "VAL", "VALE", "VALU", "VANI", "VANL", "VAPO",
    "VAR", "VATE", "VATN", "VAXX", "VB", "VBFC", "VBFCP", "VBIV", "VBKC", "VBL",
    "VBLT", "VBR", "VC", "VCAR", "VCBI", "VCEL", "VCF", "VCGH", "VCIF", "VCIT",
    "VCLT", "VCNX", "VCRA", "VCR", "VCSA", "VCSH", "VCSP", "VCST", "VCTR", "VCTT",
    "VCTY", "VCV", "VCXA", "VCXB", "VCYT", "VDC", "VDE", "VDL", "VDNI", "VEA",
    "VECO", "VEG", "VEGI", "VELT", "VENA", "VENI", "VEON", "VEPM", "VER", "VERB",
    "VERI", "VERO", "VERS", "VERT", "VET", "VEU", "VEV", "VEVO", "VFC", "VFF",
    "VFFC", "VFGN", "VFH", "VFHI", "VFLO", "VFLQ", "VFMF", "VFMV", "VFQY", "VFST",
    "VFUS", "VFVA", "VG", "VGI", "VGIT", "VGK", "VGLT", "VGM", "VGR", "VGSH",
    "VGT", "VGX", "VGZ", "VHAQ", "VHC", "VHI", "VHLD", "VHNA", "VHT", "VIA",
    "VIAC", "VIAO", "VIAV", "VICI", "VICR", "VIDI", "VIDU", "VIEW", "VIEWW",
    "VIFL", "VIG", "VIGR", "VIH", "VIIX", "VIKT", "VIMI", "VIN", "VINA", "VINC",
    "VINE", "VINO", "VINP", "VIOT", "VIPS", "VIR", "VIRC", "VIRI", "VIRT", "VISI",
    "VIST", "VISTR", "VIV", "VIVE", "VIVK", "VIVO", "VIWP", "VIXM", "VIXY", "VJET",
    "VKI", "VKQ", "VKTX", "VLA", "VLAT", "VLCN", "VLD", "VLDP", "VLDR", "VLG",
    "VLGEA", "VLO", "VLNCQ", "VLNS", "VLONA", "VLP", "VLR", "VLT", "VLTA", "VLTO",
    "VLU", "VLUE", "VLVLY", "VLY", "VLYPO", "VLYPV", "VM", "VMBS", "VMC", "VMCO",
    "VMD", "VMEO", "VMF", "VMG", "VMGA", "VMI", "VMK", "VMKTF", "VMM", "VMO",
    "VMOT", "VMP", "VMPWF", "VMQ", "VMRR", "VMS", "VMST", "VMW", "VNCE", "VNDA",
    "VNE", "VNET", "VNOM", "VNO", "VNQ", "VNRX", "VNT", "VNTR", "VNUE", "VO",
    "VOCL", "VOC", "VOD", "VOE", "VOGI", "VOL", "VOLT", "VONE", "VONG", "VONV",
    "VOO", "VOOG", "VOOV", "VOPKF", "VORG", "VOT", "VOX", "VOXX", "VOXR", "VOYA",
    "VPC", "VPCB", "VPGH", "VPG", "VPHM", "VPL", "VPLS", "VPN", "VPOP", "VPRT",
    "VPU", "VPV", "VQNX", "VR", "VRA", "VRAB", "VRAE", "VRAY", "VRCA", "VRDN",
    "VRE", "VREX", "VRI", "VRIG", "VRIK", "VRME", "VRMEW", "VRML", "VRMM", "VRNA",
    "VRNS", "VRNT", "VRNTA", "VROM", "VRSN", "VRSK", "VRST", "VRT", "VRTA", "VRTS",
    "VRTV", "VRTX", "VRTY", "VRUP", "VRUS", "VS", "VSCO", "VSDA", "VSEC", "VSEG",
    "VSH", "VSHLI", "VSLR", "VSLU", "VSM", "VSMV", "VSPR", "VSPRU", "VSPRW", "VSR",
    "VSS", "VST", "VSTA", "VSTM", "VSTNA", "VSTO", "VSTRS", "VSY", "VT", "VTA",
    "VTAQ", "VTC", "VTDRF", "VTEC", "VTEK", "VTEL", "VTEX", "VTGN", "VTI", "VTIP",
    "VTIQ", "VTIV", "VTN", "VTNS", "VTNSP", "VTNSR", "VTNSU", "VTNT", "VTOL", "VTORS",
    "VTPB", "VTR", "VTRI", "VTRN", "VTRS", "VTRU", "VTRUM", "VTRS", "VTRX", "VTS",
    "VTSI", "VTSQ", "VTSS", "VTVT", "VTWG", "VTWO", "VTWV", "VTV", "VUG", "VULL",
    "VUNE", "VUQ", "VUSB", "VUSE", "VUZI", "VV", "VVC", "VVR", "VVV", "VVWV",
    "VWA", "VWAP", "VWID", "VWND", "VWO", "VWOB", "VXF", "VXRT", "VXUS", "VYAC",
    "VYGR", "VYNE", "VYNT", "VYX", "VZ", "VZIO", "VZLA", "VZNA",
    
    "W", "WABC", "WAFD", "WAGE", "WAHYF", "WAK", "WAKE", "WAL", "WALL", "WAMP",
    "WANT", "WASH", "WAT", "WATT", "WAVC", "WAVD", "WAVE", "WAVQ", "WAVS", "WAVS",
    "WAY", "WAYW", "WB", "WBA", "WBAD", "WBC", "WBCL", "WBD", "WBEVF", "WBK",
    "WBMD", "WBNK", "WBNT", "WBS", "WBSC", "WBT", "WBTG", "WBTN", "WBX", "WCC",
    "WCG", "WCM", "WCMD", "WCN", "WCRI", "WD", "WDAY", "WDC", "WDDM", "WDH",
    "WDFC", "WDI", "WDR", "WDS", "WE", "WEA", "WEAT", "WEB", "WEBR", "WEC",
    "WEBS", "WECT", "WEFTP", "WEIS", "WEL", "WELL", "WELT", "WEN", "WENA", "WENC",
    "WENI", "WERN", "WERW", "WEST", "WET", "WETF", "WETG", "WEWKQ", "WEX", "WEYA",
    "WF", "WFCF", "WFC", "WFD", "WFG", "WFH", "WFI", "WFIQ", "WFS", "WFSL",
    "WG", "WGO", "WGSH", "WGS", "WH", "WGXEF", "WHD", "WHF", "WHFBZ", "WHG",
    "WHI", "WHJA", "WHM", "WHOL", "WHP", "WHR", "WIA", "WIG", "WILD", "WIMI",
    "WINA", "WINC", "WING", "WINT", "WISA", "WISE", "WISH", "WIT", "WITA", "WITF",
    "WIW", "WIX", "WIZZ", "WK", "WKEY", "WKHS", "WKME", "WKN", "WKSP", "WKUS",
    "WLB", "WLDN", "WLDP", "WLF", "WLFC", "WLH", "WLK", "WLKP", "WLL", "WLM",
    "WLMS", "WLP", "WLSS", "WLT", "WLTW", "WLY", "WM", "WMA", "WMAR", "WMAT",
    "WMB", "WMC", "WMCR", "WMG", "WMGI", "WMK", "WMMVF", "WMMY", "WMP", "WMS",
    "WMT", "WMW", "WNA", "WNC", "WNDY", "WNEB", "WNR", "WNS", "WNW", "WNXN",
    "WOBK", "WOKE", "WOLF", "WON", "WOOD", "WOOF", "WOR", "WORK", "WORX", "WOW",
    "WPC", "WPCF", "WPG", "WPGC", "WPM", "WPP", "WPRP", "WPRT", "WPS", "WPTBF",
    "WPX", "WR", "WRB", "WRE", "WRGL", "WRK", "WRKR", "WRLD", "WRLS", "WRN",
    "WSBC", "WSBCP", "WSBF", "WSC", "WSCO", "WSFS", "WSG", "WSGN", "WSH", "WSHP",
    "WSI", "WSM", "WSO", "WSON", "WSR", "WST", "WSTC", "WSTG", "WSTR", "WT",
    "WTAI", "WTBA", "WTBCR", "WTBF", "WTBN", "WTE", "WTER", "WTFC", "WTG", "WTI",
    "WTL", "WTM", "WTMA", "WTO", "WTRE", "WTREP", "WTRG", "WTRH", "WTS", "WTTR",
    "WTW", "WU", "WUGI", "WULF", "WUMA", "WUNR", "WUOL", "WVE", "WVFC", "WVVI",
    "WVVIP", "WW", "WWD", "WWE", "WWN", "WWNT", "WWNTW", "WWR", "WWW", "WY",
    "WYCC", "WYLD", "WYNN", "WYRA", "WYSH", "WYSHY", "WYY",
    
    "X", "XAIR", "XALL", "XAPT", "XBBB", "XBIO", "XBIT", "XCIT", "XCLR", "XCOM",
    "XCPH", "XCUR", "XDOW", "XEB", "XEBS", "XECR", "XELA", "XELB", "XEM", "XENE",
    "XENT", "XEP", "XERS", "XFAC", "XFIND", "XFLT", "XFOR", "XG", "XGI", "XGN",
    "XHB", "XHE", "XHR", "XHS", "XIACY", "XIN", "XINT", "XIT", "XKL", "XKN",
    "XL", "XLA", "XLB", "XLC", "XLE", "XLF", "XLG", "XLI", "XLK", "XLO",
    "XLP", "XLRE", "XLU", "XLV", "XLY", "XMAA", "XME", "XMHQ", "XMLV", "XMO",
    "XMPT", "XMTR", "XMVM", "XNCR", "XNET", "XNPH", "XO", "XOAI", "XOIAC", "XOMA",
    "XONE", "XOP", "XOUT", "XOXO", "XP", "XPAX", "XPC", "XPDI", "XPEL", "XPER",
    "XPEV", "XPF", "XPHB", "XPHT", "XPLG", "XPND", "XPO", "XPON", "XPOW", "XPPIX",
    "XPPT", "XPRO", "XPRS", "XPT", "XPTS", "XRDC", "XREG", "XRF", "XRI", "XRIT",
    "XRLVU", "XRM", "XRPOW", "XRSA", "XRTX", "XRTY", "XRX", "XS", "XSAWF", "XSHD",
    "XSHQ", "XSIG", "XSMO", "XSOE", "XSPA", "XSVM", "XT", "XTIA", "XTNT", "XTR",
    "XTZ", "XVGDX", "XWEB", "XXII", "XYF", "XYL", "XYLEM", "XYMOW",
    
    "Y", "YACHY", "YANG", "YATRA", "YAYO", "YCA", "YCL", "YCS", "YCST", "YDEC",
    "YELL", "YELP", "YETI", "YEXT", "YFI", "YFII", "YGE", "YGF", "YI", "YIBO",
    "YIN", "YINN", "YJ", "YJTI", "YLD", "YLDE", "YLDY", "YMM", "YMTX", "YNE",
    "YOGEW", "YOLO", "YORW", "YPF", "YQ", "YRD", "YSG", "YTEC", "YTPG", "YTRA",
    "YTV", "YUM", "YUMC", "YUNG", "YVR", "YXI", "YY", "YYAI", "YYY",
    
    "Z", "ZAK", "ZAPP", "ZB", "ZBH", "ZBRA", "ZCAN", "ZCMD", "ZD", "ZDGE",
    "ZEAL", "ZEBRA", "ZEN", "ZEPP", "ZESP", "ZEST", "ZEUS", "ZEV", "ZFOX", "ZFUS",
    "ZG", "ZGEN", "ZGI", "ZGN", "ZGNS", "ZH", "ZHOK", "ZI", "ZIG", "ZIII",
    "ZIM", "ZIMV", "ZION", "ZIOP", "ZIONP", "ZIP", "ZIXI", "ZJZZT", "ZJZ", "ZKB",
    "ZKIN", "ZKKS", "ZLC", "ZLDCU", "ZLDPW", "ZM", "ZMDA", "ZN", "ZNCP", "ZNH",
    "ZNGA", "ZNIU", "ZNT", "ZNWF", "ZNX", "ZO", "ZOMD", "ZOM", "ZOON", "ZOZOY",
    "ZP", "ZR", "ZRFY", "ZRIV", "ZS", "ZSAN", "ZSEV", "ZT", "ZTEK", "ZTO",
    "ZTR", "ZTS", "ZU", "ZUO", "ZUP", "ZURA", "ZV", "ZVSA", "ZVVW", "ZWE",
    "ZWHAU", "ZWS", "ZXAIQ", "ZYME", "ZYNE", "ZYNTX", "ZYXI",
]

# ═══════════════════════════════════════════════════════════════════════════════
# POPULAR GROWTH STOCKS & MEME STOCKS
# ═══════════════════════════════════════════════════════════════════════════════

GROWTH_AND_MEME = [
    "AFRM", "AMC", "ASTS", "BBBY", "BITF", "BLNK", "BNGO", "BYND", "CHPT", "CIFR",
    "CLNE", "CLOV", "CLSK", "COIN", "CRSR", "CVNA", "DDOG", "DNA", "DOCS", "DUOL",
    "ENPH", "EVGO", "FCEL", "FSLY", "FUBO", "FVRR", "GME", "GOEV", "GTLB", "HIMS",
    "HOOD", "HUT", "HYLN", "IONQ", "JOBY", "KIND", "KOSS", "LCID", "LI", "LILM",
    "LMND", "LOOP", "LSPD", "MARA", "MMAT", "MNMD", "MRVL", "MVST", "NAKD", "NEGG",
    "NET", "NIO", "NKLA", "NNDM", "NVAX", "OCGN", "OKTA", "OPEN", "OPAD", "OUST",
    "PACB", "PATH", "PLBY", "PLTR", "PLUG", "PRPL", "PSFE", "PTON", "QS", "RBLX",
    "RIOT", "RIVN", "RKT", "ROOT", "SENS", "SHLS", "SKLZ", "SLQT", "SNAP", "SNOW",
    "SOFI", "SONO", "SPCE", "SPWR", "SQ", "STEM", "TELL", "TLRY", "TOST", "TTD",
    "U", "UPST", "UWMC", "VLD", "VRM", "VUZI", "WKHS", "WISH", "XPEV", "ZM",
    "AEHR", "ARQT", "BARK", "BGFV", "BILL", "BROS", "CANO", "CROX", "DRS", "EDIT",
    "EMKR", "EVTL", "GDRX", "GNUS", "GRWG", "JYNT", "KERN", "LIDR", "LFMD", "LOVE",
    "MNST", "MSOS", "NCNO", "NRXP", "PAYO", "PGEN", "PRCH", "PUBM", "RAIN", "RVPH",
    "S", "SEER", "SITM", "SUNW", "TTCF", "VCEL", "VNET", "WE", "WEJO", "WIMI",
    "WOOF", "XELA", "YEXT", "ZETA", "ZG", "ZI", "ZNGA", "BTBT", "IREN", "MARA",
    "RIOT", "HIVE", "BITF", "CLSK", "ARBK", "CORZ", "GREE", "HUT", "DMGI",
]

# ═══════════════════════════════════════════════════════════════════════════════
# MAJOR ETFs
# ═══════════════════════════════════════════════════════════════════════════════

ETFS = [
    # Major Index ETFs
    "SPY", "QQQ", "IWM", "DIA", "IVV", "VOO", "VTI", "VTV", "VUG", "VIG",
    "IJH", "IJR", "MDY", "IWF", "IWD", "IWO", "IWN", "RSP", "SPLG", "SCHX",
    
    # Dividend ETFs
    "SCHD", "JEPI", "VYM", "DVY", "SDY", "NOBL", "DGRO", "DGRW", "HDV", "SPYD",
    
    # Sector ETFs
    "XLF", "XLE", "XLK", "XLV", "XLI", "XLY", "XLP", "XLU", "XLB", "XLC",
    "XLRE", "VNQ", "IYR", "VGT", "VHT", "VFH", "VDE", "VAW", "VIS", "VCR",
    
    # Innovation & Thematic
    "ARKK", "ARKG", "ARKF", "ARKQ", "ARKW", "ARKX", "MOON", "BUZZ", "IZRL", "PRNT",
    
    # Leveraged & Inverse
    "SOXL", "TQQQ", "SQQQ", "SPXL", "SPXS", "TNA", "TZA", "FAS", "FAZ", "LABU",
    "LABD", "UVXY", "VXX", "SVXY", "SOXS", "TECL", "TECS", "UPRO", "SPXU", "SSO",
    
    # Commodities
    "GLD", "SLV", "GDX", "GDXJ", "USO", "UNG", "PPLT", "PALL", "DBA", "DBC",
    
    # International
    "EEM", "EFA", "VWO", "IEMG", "FXI", "KWEB", "MCHI", "INDA", "EWJ", "EWZ",
    "EWG", "EWU", "EWT", "EWY", "EWH", "EWW", "EWC", "EWA", "VEA", "VXUS",
    
    # Bonds
    "TLT", "IEF", "SHY", "BND", "AGG", "LQD", "HYG", "JNK", "VCIT", "VCSH",
    "VGIT", "VGLT", "GOVT", "MUB", "TIP", "BNDX", "EMB",
    
    # Currency
    "UUP", "FXE", "FXY", "FXB", "FXA", "FXC",
    
    # Crypto Related
    "BITO", "GBTC", "ETHE", "MSTR",
]

# ═══════════════════════════════════════════════════════════════════════════════
# HELPER FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════════════

def get_full_universe() -> list[str]:
    """Get complete stock universe (~6,000+ stocks)"""
    all_symbols = set()
    all_symbols.update(SP500)
    all_symbols.update(SP400_MIDCAP)
    all_symbols.update(SP600_SMALLCAP)
    all_symbols.update(RUSSELL_2000_ADDITIONS)
    all_symbols.update(RUSSELL_2000_MZ)
    all_symbols.update(GROWTH_AND_MEME)
    all_symbols.update(ETFS)
    
    # Clean and validate symbols
    valid_symbols = {s.upper().strip() for s in all_symbols 
                     if s and isinstance(s, str) and len(s) <= 6 and s.isalpha() or '-' in s}
    
    return sorted(list(valid_symbols))


def get_by_category(category: str) -> list[str]:
    """Get stocks by category"""
    categories = {
        "sp500": SP500,
        "largecap": SP500,
        "midcap": SP400_MIDCAP,
        "smallcap": SP600_SMALLCAP,
        "microcap": RUSSELL_2000_ADDITIONS + GROWTH_AND_MEME,
        "etf": ETFS,
        "growth": GROWTH_AND_MEME,
        "meme": GROWTH_AND_MEME,
    }
    return categories.get(category.lower(), get_full_universe())


def get_universe_summary() -> dict:
    """Get summary of universe composition"""
    return {
        "sp500_largecap": len(SP500),
        "sp400_midcap": len(SP400_MIDCAP),
        "sp600_smallcap": len(SP600_SMALLCAP),
        "russell_additions": len(RUSSELL_2000_ADDITIONS),
        "russell_mz": len(RUSSELL_2000_MZ),
        "growth_meme": len(GROWTH_AND_MEME),
        "etfs": len(ETFS),
        "total_unique": len(get_full_universe()),
    }


# Summary for quick access
UNIVERSE_SUMMARY = get_universe_summary()


if __name__ == "__main__":
    summary = get_universe_summary()
    print("=" * 60)
    print("           COMPREHENSIVE STOCK UNIVERSE SUMMARY")
    print("=" * 60)
    print(f"  S&P 500 (Large Cap):        {summary['sp500_largecap']:>5,} stocks")
    print(f"  S&P 400 (Mid Cap):          {summary['sp400_midcap']:>5,} stocks")
    print(f"  S&P 600 (Small Cap):        {summary['sp600_smallcap']:>5,} stocks")
    print(f"  Russell 2000 Adds (A-L):    {summary['russell_additions']:>5,} stocks")
    print(f"  Russell 2000 Adds (M-Z):    {summary['russell_mz']:>5,} stocks")
    print(f"  Growth/Meme Stocks:         {summary['growth_meme']:>5,} stocks")
    print(f"  ETFs:                       {summary['etfs']:>5,} ETFs")
    print("-" * 60)
    print(f"  TOTAL UNIQUE SYMBOLS:       {summary['total_unique']:>5,}")
    print("=" * 60)
    
    # Estimate scan time
    total = summary['total_unique']
    batches = total // 50 + 1
    min_time = batches * 3 // 60
    max_time = batches * 8 // 60
    print(f"\n  📊 Estimated scan time: {min_time}-{max_time} minutes")
    print(f"  🔄 Refresh schedule: Every 30 minutes")
    print(f"  ⚡ During market hours: Near real-time data")
