"use client";

import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { Edit3, Trash2 } from "lucide-react";

interface Idea {
    id: string;
    ticker: string;
    title: string;
    notes: string;
    createdAt: string;
    updatedAt: string;
}

function IdeaCard({ idea, onEdit, onDelete }: { idea: Idea; onEdit: () => void; onDelete: () => void }) {
    return (
        <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="idea-card"
        >
            <div className="idea-header">
                <div className="idea-ticker-badge">{idea.ticker}</div>
                <div className="idea-actions">
                    <button onClick={onEdit} className="idea-action-btn">
                        <Edit3 size={14} />
                    </button>
                    <button onClick={onDelete} className="idea-action-btn danger">
                        <Trash2 size={14} />
                    </button>
                </div>
            </div>
            <h3 className="idea-title">{idea.title}</h3>
            <p className="idea-notes" style={{ whiteSpace: 'pre-wrap' }}>{idea.notes}</p>
            <div className="idea-footer">
                <span>Created: {idea.createdAt}</span>
                <span>Updated: {idea.updatedAt}</span>
            </div>
        </motion.div>
    );
}

export function IdeasPage() {
    const [ideas, setIdeas] = useState<Idea[]>([]);
    const [isLoading, setIsLoading] = useState(true);

    const API_BASE = import.meta.env.VITE_API_URL || 'http://localhost:8000/api';

    const [scanTicker, setScanTicker] = useState("");
    const [isScanning, setIsScanning] = useState(false);
    const [scanResult, setScanResult] = useState<any>(null);

    const fetchIdeas = async () => {
        try {
            setIsLoading(true);
            const response = await fetch(`${API_BASE}/ideas`);
            if (response.ok) {
                const data = await response.json();
                setIdeas(data);
            }
        } catch (error) {
            console.error("Failed to fetch ideas:", error);
        } finally {
            setIsLoading(false);
        }
    };

    const handleRunScan = async () => {
        if (!scanTicker) return;
        setIsScanning(true);
        setScanResult(null);
        try {
            const response = await fetch(`${API_BASE}/intelligence/scan`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ symbol: scanTicker })
            });
            const result = await response.json();
            setScanResult(result);
            if (result.status === 'signal') {
                fetchIdeas(); // Reload ideas
            }
        } catch (error) {
            console.error("Scan failed:", error);
        } finally {
            setIsScanning(false);
        }
    };

    useEffect(() => {
        fetchIdeas();
    }, []);

    const handleDelete = (id: string) => {
        setIdeas(ideas.filter((i) => i.id !== id));
    };

    return (
        <div className="page-container">
            <div className="page-header" style={{ marginBottom: '2rem' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                    <div>
                        <h1 className="page-title">Strategist Reports</h1>
                        <p className="page-subtitle">Deep research generated by the Dual-Agent system</p>
                    </div>

                    <div style={{ display: 'flex', gap: '10px' }}>
                        <button onClick={fetchIdeas} className="idea-action-btn" style={{ background: 'rgba(59, 130, 246, 0.1)', color: '#3b82f6', border: '1px solid #3b82f6', alignSelf: 'center' }}>
                            Refresh List
                        </button>
                    </div>
                </div>

                {/* Manual Scanner UI */}
                <div style={{
                    marginTop: '1.5rem',
                    padding: '1.25rem',
                    backgroundColor: 'rgba(30, 41, 59, 0.5)',
                    borderRadius: '12px',
                    border: '1px solid var(--card-border)',
                }}>
                    <h3 style={{ fontSize: '1rem', fontWeight: 600, color: 'var(--fg)', marginBottom: '0.75rem' }}>Run Manual Intelligence Scan</h3>
                    <div style={{ display: 'flex', gap: '12px' }}>
                        <input
                            type="text"
                            placeholder="Enter Ticker (e.g. NVDA)"
                            value={scanTicker}
                            onChange={(e) => setScanTicker(e.target.value.toUpperCase())}
                            style={{
                                flex: 1,
                                background: 'var(--bg)',
                                border: '1px solid var(--card-border)',
                                borderRadius: '8px',
                                padding: '0.625rem 1rem',
                                color: 'var(--fg)',
                                outline: 'none'
                            }}
                        />
                        <button
                            onClick={handleRunScan}
                            disabled={isScanning || !scanTicker}
                            style={{
                                padding: '0.625rem 1.5rem',
                                background: 'var(--accent)',
                                color: '#000',
                                fontWeight: 700,
                                borderRadius: '8px',
                                opacity: isScanning ? 0.6 : 1,
                                cursor: isScanning ? 'wait' : 'pointer'
                            }}
                        >
                            {isScanning ? 'Scanning...' : 'Start Intelligence Scan'}
                        </button>
                    </div>

                    {isScanning && (
                        <div style={{ marginTop: '1rem', display: 'flex', alignItems: 'center', gap: '10px' }}>
                            <div className="thinking-indicator" style={{ margin: 0 }}>Scout is analyzing market data...</div>
                        </div>
                    )}

                    {scanResult && (
                        <div style={{
                            marginTop: '1rem',
                            padding: '0.75rem',
                            borderRadius: '8px',
                            fontSize: '0.875rem',
                            backgroundColor: scanResult.status === 'signal' ? 'rgba(0, 255, 133, 0.1)' : 'rgba(107, 114, 128, 0.1)',
                            color: scanResult.status === 'signal' ? 'var(--accent)' : '#6b7280',
                            border: `1px solid ${scanResult.status === 'signal' ? 'var(--accent)' : 'var(--card-border)'}`
                        }}>
                            {scanResult.status === 'signal'
                                ? `🚀 SIGNAL DETECTED for ${scanResult.symbol}! Full report generated below.`
                                : `No high-confidence signal detected for ${scanResult.symbol}. Scout Insight: ${scanResult.scout_insight}`
                            }
                        </div>
                    )}
                </div>
            </div>

            {isLoading ? (
                <div style={{ display: 'flex', justifyContent: 'center', padding: '3rem' }}>
                    <div className="thinking-indicator">Scanning for intelligence...</div>
                </div>
            ) : (
                <div className="ideas-grid">
                    {ideas.length === 0 ? (
                        <div style={{ gridColumn: '1/-1', textAlign: 'center', padding: '3rem', color: '#6b7280' }}>
                            No reports generated yet. The Scout is currently scanning the market.
                        </div>
                    ) : (
                        ideas.map((idea) => (
                            <IdeaCard
                                key={idea.id}
                                idea={idea}
                                onEdit={() => { }}
                                onDelete={() => handleDelete(idea.id)}
                            />
                        ))
                    )}
                </div>
            )}
        </div>
    );
}

export default IdeasPage;
